-- Catálogo inicial de ingredientes (clasificado). Generado con IA.
insert into ingredients (name, normalized_name, category) values
  ('Manzana golden', 'manzana golden', 'Frutas'),
  ('Manzana granny smith', 'manzana granny smith', 'Frutas'),
  ('Pera conferencia', 'pera conferencia', 'Frutas'),
  ('Pera ercolina', 'pera ercolina', 'Frutas'),
  ('Plátano de canarias', 'platano de canarias', 'Frutas'),
  ('Naranja de mesa', 'naranja de mesa', 'Frutas'),
  ('Naranja de zumo', 'naranja de zumo', 'Frutas'),
  ('Mandarina clementina', 'mandarina clementina', 'Frutas'),
  ('Limón amarillo', 'limon amarillo', 'Frutas'),
  ('Lima', 'lima', 'Frutas'),
  ('Uva blanca', 'uva blanca', 'Frutas'),
  ('Uva tinta', 'uva tinta', 'Frutas'),
  ('Melocotón amarillo', 'melocoton amarillo', 'Frutas'),
  ('Melocotón paraguayo', 'melocoton paraguayo', 'Frutas'),
  ('Nectarina', 'nectarina', 'Frutas'),
  ('Albaricoque', 'albaricoque', 'Frutas'),
  ('Ciruela claudia', 'ciruela claudia', 'Frutas'),
  ('Ciruela roja', 'ciruela roja', 'Frutas'),
  ('Cereza', 'cereza', 'Frutas'),
  ('Picota', 'picota', 'Frutas'),
  ('Fresa', 'fresa', 'Frutas'),
  ('Fresón', 'freson', 'Frutas'),
  ('Melón piel de sapo', 'melon piel de sapo', 'Frutas'),
  ('Sandía', 'sandia', 'Frutas'),
  ('Higo', 'higo', 'Frutas'),
  ('Breva', 'breva', 'Frutas'),
  ('Granada', 'granada', 'Frutas'),
  ('Membrillo', 'membrillo', 'Frutas'),
  ('Piña', 'pina', 'Frutas'),
  ('Aguacate', 'aguacate', 'Frutas'),
  ('Patata', 'patata', 'Verduras y hortalizas'),
  ('Cebolla blanca', 'cebolla blanca', 'Verduras y hortalizas'),
  ('Cebolla morada', 'cebolla morada', 'Verduras y hortalizas'),
  ('Ajo', 'ajo', 'Verduras y hortalizas'),
  ('Tomate pera', 'tomate pera', 'Verduras y hortalizas'),
  ('Tomate rama', 'tomate rama', 'Verduras y hortalizas'),
  ('Pimiento verde', 'pimiento verde', 'Verduras y hortalizas'),
  ('Pimiento rojo', 'pimiento rojo', 'Verduras y hortalizas'),
  ('Calabacín', 'calabacin', 'Verduras y hortalizas'),
  ('Berenjena', 'berenjena', 'Verduras y hortalizas'),
  ('Zanahoria', 'zanahoria', 'Verduras y hortalizas'),
  ('Judía verde plana', 'judia verde plana', 'Verduras y hortalizas'),
  ('Judía verde redonda', 'judia verde redonda', 'Verduras y hortalizas'),
  ('Espárrago triguero', 'esparrago triguero', 'Verduras y hortalizas'),
  ('Alcachofa', 'alcachofa', 'Verduras y hortalizas'),
  ('Espinaca', 'espinaca', 'Verduras y hortalizas'),
  ('Acelga', 'acelga', 'Verduras y hortalizas'),
  ('Coliflor', 'coliflor', 'Verduras y hortalizas'),
  ('Brócoli', 'brocoli', 'Verduras y hortalizas'),
  ('Calabaza', 'calabaza', 'Verduras y hortalizas'),
  ('Pepino', 'pepino', 'Verduras y hortalizas'),
  ('Lechuga romana', 'lechuga romana', 'Verduras y hortalizas'),
  ('Lechuga hoja de roble', 'lechuga hoja de roble', 'Verduras y hortalizas'),
  ('Puerro', 'puerro', 'Verduras y hortalizas'),
  ('Apio', 'apio', 'Verduras y hortalizas'),
  ('Guisante', 'guisante', 'Verduras y hortalizas'),
  ('Haba', 'haba', 'Verduras y hortalizas'),
  ('Cardo', 'cardo', 'Verduras y hortalizas'),
  ('Champiñón', 'champinon', 'Verduras y hortalizas'),
  ('Setas ostra', 'setas ostra', 'Verduras y hortalizas'),
  ('Solomillo de cerdo', 'solomillo de cerdo', 'Carnes'),
  ('Lomo de cerdo', 'lomo de cerdo', 'Carnes'),
  ('Secreto ibérico', 'secreto iberico', 'Carnes'),
  ('Presa ibérica', 'presa iberica', 'Carnes'),
  ('Pluma ibérica', 'pluma iberica', 'Carnes'),
  ('Panceta de cerdo', 'panceta de cerdo', 'Carnes'),
  ('Costilla de cerdo', 'costilla de cerdo', 'Carnes'),
  ('Chorizo fresco', 'chorizo fresco', 'Carnes'),
  ('Morcilla de arroz', 'morcilla de arroz', 'Carnes'),
  ('Morcilla de cebolla', 'morcilla de cebolla', 'Carnes'),
  ('Jamón serrano', 'jamon serrano', 'Carnes'),
  ('Jamón ibérico', 'jamon iberico', 'Carnes'),
  ('Chuletón de ternera', 'chuleton de ternera', 'Carnes'),
  ('Solomillo de ternera', 'solomillo de ternera', 'Carnes'),
  ('Rabito de ternera', 'rabito de ternera', 'Carnes'),
  ('Callos de ternera', 'callos de ternera', 'Carnes'),
  ('Pollo entero', 'pollo entero', 'Carnes'),
  ('Pechuga de pollo', 'pechuga de pollo', 'Carnes'),
  ('Muslo de pollo', 'muslo de pollo', 'Carnes'),
  ('Alita de pollo', 'alita de pollo', 'Carnes'),
  ('Conejo de campo', 'conejo de campo', 'Carnes'),
  ('Codorniz', 'codorniz', 'Carnes'),
  ('Cordero lechal', 'cordero lechal', 'Carnes'),
  ('Chuletilla de cordero', 'chuletilla de cordero', 'Carnes'),
  ('Paletilla de cordero', 'paletilla de cordero', 'Carnes'),
  ('Magro de cerdo', 'magro de cerdo', 'Carnes'),
  ('Tocino ibérico', 'tocino iberico', 'Carnes'),
  ('Salchicha fresca', 'salchicha fresca', 'Carnes'),
  ('Longaniza', 'longaniza', 'Carnes'),
  ('Lacón', 'lacon', 'Carnes'),
  ('Merluza', 'merluza', 'Pescados y mariscos'),
  ('Bacalao fresco', 'bacalao fresco', 'Pescados y mariscos'),
  ('Bacalao desalado', 'bacalao desalado', 'Pescados y mariscos'),
  ('Rape', 'rape', 'Pescados y mariscos'),
  ('Lenguado', 'lenguado', 'Pescados y mariscos'),
  ('Dorada', 'dorada', 'Pescados y mariscos'),
  ('Lubina', 'lubina', 'Pescados y mariscos'),
  ('Rodaballo', 'rodaballo', 'Pescados y mariscos'),
  ('Atún rojo', 'atun rojo', 'Pescados y mariscos'),
  ('Bonito del norte', 'bonito del norte', 'Pescados y mariscos'),
  ('Boquerón', 'boqueron', 'Pescados y mariscos'),
  ('Sardina', 'sardina', 'Pescados y mariscos'),
  ('Caballa', 'caballa', 'Pescados y mariscos'),
  ('Anchoa', 'anchoa', 'Pescados y mariscos'),
  ('Gambón', 'gambon', 'Pescados y mariscos'),
  ('Gamba blanca', 'gamba blanca', 'Pescados y mariscos'),
  ('Gamba roja', 'gamba roja', 'Pescados y mariscos'),
  ('Langostino', 'langostino', 'Pescados y mariscos'),
  ('Cigala', 'cigala', 'Pescados y mariscos'),
  ('Bogavante', 'bogavante', 'Pescados y mariscos'),
  ('Langosta', 'langosta', 'Pescados y mariscos'),
  ('Mejillón', 'mejillon', 'Pescados y mariscos'),
  ('Almeja babosa', 'almeja babosa', 'Pescados y mariscos'),
  ('Almeja fina', 'almeja fina', 'Pescados y mariscos'),
  ('Berberecho', 'berberecho', 'Pescados y mariscos'),
  ('Navaja', 'navaja', 'Pescados y mariscos'),
  ('Vieira', 'vieira', 'Pescados y mariscos'),
  ('Pulpo', 'pulpo', 'Pescados y mariscos'),
  ('Calamar', 'calamar', 'Pescados y mariscos'),
  ('Sepia', 'sepia', 'Pescados y mariscos'),
  ('Leche entera', 'leche entera', 'Lácteos y huevos'),
  ('Leche semidesnatada', 'leche semidesnatada', 'Lácteos y huevos'),
  ('Leche desnatada', 'leche desnatada', 'Lácteos y huevos'),
  ('Nata para montar', 'nata para montar', 'Lácteos y huevos'),
  ('Nata para cocinar', 'nata para cocinar', 'Lácteos y huevos'),
  ('Mantequilla con sal', 'mantequilla con sal', 'Lácteos y huevos'),
  ('Mantequilla sin sal', 'mantequilla sin sal', 'Lácteos y huevos'),
  ('Queso manchego semicurado', 'queso manchego semicurado', 'Lácteos y huevos'),
  ('Queso manchego curado', 'queso manchego curado', 'Lácteos y huevos'),
  ('Queso fresco', 'queso fresco', 'Lácteos y huevos'),
  ('Queso de cabrales', 'queso de cabrales', 'Lácteos y huevos'),
  ('Queso tetilla', 'queso tetilla', 'Lácteos y huevos'),
  ('Queso idiazábal', 'queso idiazabal', 'Lácteos y huevos'),
  ('Queso mahón', 'queso mahon', 'Lácteos y huevos'),
  ('Queso burgos', 'queso burgos', 'Lácteos y huevos'),
  ('Requesón', 'requeson', 'Lácteos y huevos'),
  ('Yogur natural', 'yogur natural', 'Lácteos y huevos'),
  ('Yogur griego', 'yogur griego', 'Lácteos y huevos'),
  ('Huevo de gallina', 'huevo de gallina', 'Lácteos y huevos'),
  ('Huevo de codorniz', 'huevo de codorniz', 'Lácteos y huevos'),
  ('Clara de huevo', 'clara de huevo', 'Lácteos y huevos'),
  ('Yema de huevo', 'yema de huevo', 'Lácteos y huevos'),
  ('Queso rulo de cabra', 'queso rulo de cabra', 'Lácteos y huevos'),
  ('Queso crema', 'queso crema', 'Lácteos y huevos'),
  ('Queso parmesano', 'queso parmesano', 'Lácteos y huevos'),
  ('Queso emmental', 'queso emmental', 'Lácteos y huevos'),
  ('Queso mozzarella', 'queso mozzarella', 'Lácteos y huevos'),
  ('Leche evaporada', 'leche evaporada', 'Lácteos y huevos'),
  ('Leche condensada', 'leche condensada', 'Lácteos y huevos'),
  ('Cuajada', 'cuajada', 'Lácteos y huevos'),
  ('Arroz bomba', 'arroz bomba', 'Cereales, pan y pasta'),
  ('Arroz basmati', 'arroz basmati', 'Cereales, pan y pasta'),
  ('Arroz integral', 'arroz integral', 'Cereales, pan y pasta'),
  ('Arroz redondo', 'arroz redondo', 'Cereales, pan y pasta'),
  ('Pan de hogaza', 'pan de hogaza', 'Cereales, pan y pasta'),
  ('Pan de barra', 'pan de barra', 'Cereales, pan y pasta'),
  ('Pan integral', 'pan integral', 'Cereales, pan y pasta'),
  ('Pan de centeno', 'pan de centeno', 'Cereales, pan y pasta'),
  ('Pan de molde', 'pan de molde', 'Cereales, pan y pasta'),
  ('Pasta espagueti', 'pasta espagueti', 'Cereales, pan y pasta'),
  ('Pasta macarron', 'pasta macarron', 'Cereales, pan y pasta'),
  ('Pasta tallarines', 'pasta tallarines', 'Cereales, pan y pasta'),
  ('Pasta de sopa', 'pasta de sopa', 'Cereales, pan y pasta'),
  ('Pasta lasana', 'pasta lasana', 'Cereales, pan y pasta'),
  ('Avena en copos', 'avena en copos', 'Cereales, pan y pasta'),
  ('Cebada perlada', 'cebada perlada', 'Cereales, pan y pasta'),
  ('Quinoa', 'quinoa', 'Cereales, pan y pasta'),
  ('Cuscús', 'cuscus', 'Cereales, pan y pasta'),
  ('Harina de trigo', 'harina de trigo', 'Cereales, pan y pasta'),
  ('Harina de fuerza', 'harina de fuerza', 'Cereales, pan y pasta'),
  ('Harina de maiz', 'harina de maiz', 'Cereales, pan y pasta'),
  ('Maiz en grano', 'maiz en grano', 'Cereales, pan y pasta'),
  ('Pan rallado', 'pan rallado', 'Cereales, pan y pasta'),
  ('Picos de pan', 'picos de pan', 'Cereales, pan y pasta'),
  ('Rosquilletas', 'rosquilletas', 'Cereales, pan y pasta'),
  ('Tortitas de arroz', 'tortitas de arroz', 'Cereales, pan y pasta'),
  ('Bulgur', 'bulgur', 'Cereales, pan y pasta'),
  ('Mijo', 'mijo', 'Cereales, pan y pasta'),
  ('Trigo sarraceno', 'trigo sarraceno', 'Cereales, pan y pasta'),
  ('Fideo cabellin', 'fideo cabellin', 'Cereales, pan y pasta'),
  ('Garbanzo castellano', 'garbanzo castellano', 'Legumbres'),
  ('Garbanzo pedrosillano', 'garbanzo pedrosillano', 'Legumbres'),
  ('Garbanzo lechoso', 'garbanzo lechoso', 'Legumbres'),
  ('Lenteja pardina', 'lenteja pardina', 'Legumbres'),
  ('Lenteja verdina', 'lenteja verdina', 'Legumbres'),
  ('Lenteja castellana', 'lenteja castellana', 'Legumbres'),
  ('Lenteja caviar', 'lenteja caviar', 'Legumbres'),
  ('Alubia blanca riñón', 'alubia blanca rinon', 'Legumbres'),
  ('Alubia blanca plancheta', 'alubia blanca plancheta', 'Legumbres'),
  ('Alubia blanca alubión', 'alubia blanca alubion', 'Legumbres'),
  ('Alubia pinta', 'alubia pinta', 'Legumbres'),
  ('Alubia roja de Tolosa', 'alubia roja de tolosa', 'Legumbres'),
  ('Alubia carilla', 'alubia carilla', 'Legumbres'),
  ('Alubia pocha', 'alubia pocha', 'Legumbres'),
  ('Alubia ganxet', 'alubia ganxet', 'Legumbres'),
  ('Habas frescas', 'habas frescas', 'Legumbres'),
  ('Haba seca', 'haba seca', 'Legumbres'),
  ('Soja verde', 'soja verde', 'Legumbres'),
  ('Altramuz', 'altramuz', 'Legumbres'),
  ('Guisante seco', 'guisante seco', 'Legumbres'),
  ('Guisante partido', 'guisante partido', 'Legumbres'),
  ('Garbanzo garbanzuelo', 'garbanzo garbanzuelo', 'Legumbres'),
  ('Lenteja rubia', 'lenteja rubia', 'Legumbres'),
  ('Alubia arrocina', 'alubia arrocina', 'Legumbres'),
  ('Alubia verdina', 'alubia verdina', 'Legumbres'),
  ('Haba baby', 'haba baby', 'Legumbres'),
  ('Lenteja beluga', 'lenteja beluga', 'Legumbres'),
  ('Garbanzo tolosano', 'garbanzo tolosano', 'Legumbres'),
  ('Alubia negra', 'alubia negra', 'Legumbres'),
  ('Judión de la granja', 'judion de la granja', 'Legumbres'),
  ('Almendra cruda', 'almendra cruda', 'Frutos secos y semillas'),
  ('Almendra tostada', 'almendra tostada', 'Frutos secos y semillas'),
  ('Almendra laminada', 'almendra laminada', 'Frutos secos y semillas'),
  ('Avellana', 'avellana', 'Frutos secos y semillas'),
  ('Nuez', 'nuez', 'Frutos secos y semillas'),
  ('Pistacho', 'pistacho', 'Frutos secos y semillas'),
  ('Piñón', 'pinon', 'Frutos secos y semillas'),
  ('Cacahuete', 'cacahuete', 'Frutos secos y semillas'),
  ('Anacardo', 'anacardo', 'Frutos secos y semillas'),
  ('Nuez de macadamia', 'nuez de macadamia', 'Frutos secos y semillas'),
  ('Pipa de girasol', 'pipa de girasol', 'Frutos secos y semillas'),
  ('Semilla de calabaza', 'semilla de calabaza', 'Frutos secos y semillas'),
  ('Sésamo blanco', 'sesamo blanco', 'Frutos secos y semillas'),
  ('Sésamo negro', 'sesamo negro', 'Frutos secos y semillas'),
  ('Semilla de chía', 'semilla de chia', 'Frutos secos y semillas'),
  ('Semilla de lino', 'semilla de lino', 'Frutos secos y semillas'),
  ('Semilla de amapola', 'semilla de amapola', 'Frutos secos y semillas'),
  ('Castaña', 'castana', 'Frutos secos y semillas'),
  ('Castaña pilonga', 'castana pilonga', 'Frutos secos y semillas'),
  ('Nuez pecana', 'nuez pecana', 'Frutos secos y semillas'),
  ('Almendra marcona', 'almendra marcona', 'Frutos secos y semillas'),
  ('Almendra largueta', 'almendra largueta', 'Frutos secos y semillas'),
  ('Avellana tostada', 'avellana tostada', 'Frutos secos y semillas'),
  ('Pipa de girasol tostada', 'pipa de girasol tostada', 'Frutos secos y semillas'),
  ('Pipa de calabaza tostada', 'pipa de calabaza tostada', 'Frutos secos y semillas'),
  ('Sésamo tostado', 'sesamo tostado', 'Frutos secos y semillas'),
  ('Semilla de lino dorado', 'semilla de lino dorado', 'Frutos secos y semillas'),
  ('Semilla de lino marrón', 'semilla de lino marron', 'Frutos secos y semillas'),
  ('Pistacho pelado', 'pistacho pelado', 'Frutos secos y semillas'),
  ('Cacahuete tostado', 'cacahuete tostado', 'Frutos secos y semillas'),
  ('Azafrán', 'azafran', 'Especias y hierbas'),
  ('Pimentón dulce', 'pimenton dulce', 'Especias y hierbas'),
  ('Pimentón picante', 'pimenton picante', 'Especias y hierbas'),
  ('Pimentón ahumado', 'pimenton ahumado', 'Especias y hierbas'),
  ('Orégano seco', 'oregano seco', 'Especias y hierbas'),
  ('Tomillo fresco', 'tomillo fresco', 'Especias y hierbas'),
  ('Romero fresco', 'romero fresco', 'Especias y hierbas'),
  ('Perejil plano', 'perejil plano', 'Especias y hierbas'),
  ('Laurel seco', 'laurel seco', 'Especias y hierbas'),
  ('Comino molido', 'comino molido', 'Especias y hierbas'),
  ('Clavo', 'clavo', 'Especias y hierbas'),
  ('Canela en rama', 'canela en rama', 'Especias y hierbas'),
  ('Nuez moscada', 'nuez moscada', 'Especias y hierbas'),
  ('Pimienta negra', 'pimienta negra', 'Especias y hierbas'),
  ('Pimienta blanca', 'pimienta blanca', 'Especias y hierbas'),
  ('Pimienta de cayena', 'pimienta de cayena', 'Especias y hierbas'),
  ('Ajo morado', 'ajo morado', 'Especias y hierbas'),
  ('Ajo blanco', 'ajo blanco', 'Especias y hierbas'),
  ('Cebollino', 'cebollino', 'Especias y hierbas'),
  ('Menta', 'menta', 'Especias y hierbas'),
  ('Hierbabuena', 'hierbabuena', 'Especias y hierbas'),
  ('Albahaca', 'albahaca', 'Especias y hierbas'),
  ('Anís en grano', 'anis en grano', 'Especias y hierbas'),
  ('Cilantro', 'cilantro', 'Especias y hierbas'),
  ('Sal marina', 'sal marina', 'Especias y hierbas'),
  ('Sal gorda', 'sal gorda', 'Especias y hierbas'),
  ('Azafrán en hebra', 'azafran en hebra', 'Especias y hierbas'),
  ('Ñora', 'nora', 'Especias y hierbas'),
  ('Aceite de oliva virgen extra', 'aceite de oliva virgen extra', 'Aceites, vinagres y salsas'),
  ('Aceite de oliva suave', 'aceite de oliva suave', 'Aceites, vinagres y salsas'),
  ('Aceite de girasol', 'aceite de girasol', 'Aceites, vinagres y salsas'),
  ('Vinagre de jerez', 'vinagre de jerez', 'Aceites, vinagres y salsas'),
  ('Vinagre de vino blanco', 'vinagre de vino blanco', 'Aceites, vinagres y salsas'),
  ('Vinagre de vino tinto', 'vinagre de vino tinto', 'Aceites, vinagres y salsas'),
  ('Vinagre de manzana', 'vinagre de manzana', 'Aceites, vinagres y salsas'),
  ('Vinagre de módena', 'vinagre de modena', 'Aceites, vinagres y salsas'),
  ('Salsa de tomate frito', 'salsa de tomate frito', 'Aceites, vinagres y salsas'),
  ('Salsa de tomate triturado', 'salsa de tomate triturado', 'Aceites, vinagres y salsas'),
  ('Salsa alioli', 'salsa alioli', 'Aceites, vinagres y salsas'),
  ('Salsa romesco', 'salsa romesco', 'Aceites, vinagres y salsas'),
  ('Salsa brava', 'salsa brava', 'Aceites, vinagres y salsas'),
  ('Salsa vizcaína', 'salsa vizcaina', 'Aceites, vinagres y salsas'),
  ('Salsa de soja', 'salsa de soja', 'Aceites, vinagres y salsas'),
  ('Mayonesa', 'mayonesa', 'Aceites, vinagres y salsas'),
  ('Mostaza antigua', 'mostaza antigua', 'Aceites, vinagres y salsas'),
  ('Mostaza de dijon', 'mostaza de dijon', 'Aceites, vinagres y salsas'),
  ('Salsa perrins', 'salsa perrins', 'Aceites, vinagres y salsas'),
  ('Salsa tabasco', 'salsa tabasco', 'Aceites, vinagres y salsas'),
  ('Aceite de sésamo', 'aceite de sesamo', 'Aceites, vinagres y salsas'),
  ('Vinagre de arroz', 'vinagre de arroz', 'Aceites, vinagres y salsas'),
  ('Salsa agridulce', 'salsa agridulce', 'Aceites, vinagres y salsas'),
  ('Reducción de vinagre balsámico', 'reduccion de vinagre balsamico', 'Aceites, vinagres y salsas'),
  ('Aceite de trufa', 'aceite de trufa', 'Aceites, vinagres y salsas'),
  ('Salsa barbacoa', 'salsa barbacoa', 'Aceites, vinagres y salsas'),
  ('Salsa pesto', 'salsa pesto', 'Aceites, vinagres y salsas'),
  ('Aceite de ajo', 'aceite de ajo', 'Aceites, vinagres y salsas'),
  ('Vinagre de sidra', 'vinagre de sidra', 'Aceites, vinagres y salsas'),
  ('Salsa picante', 'salsa picante', 'Aceites, vinagres y salsas'),
  ('Sal fina', 'sal fina', 'Condimentos y edulcorantes'),
  ('Azucar blanco', 'azucar blanco', 'Condimentos y edulcorantes'),
  ('Azucar moreno', 'azucar moreno', 'Condimentos y edulcorantes'),
  ('Miel de milflores', 'miel de milflores', 'Condimentos y edulcorantes'),
  ('Miel de romero', 'miel de romero', 'Condimentos y edulcorantes'),
  ('Laurel', 'laurel', 'Condimentos y edulcorantes'),
  ('Oregano', 'oregano', 'Condimentos y edulcorantes'),
  ('Tomillo', 'tomillo', 'Condimentos y edulcorantes'),
  ('Romero', 'romero', 'Condimentos y edulcorantes'),
  ('Perejil', 'perejil', 'Condimentos y edulcorantes'),
  ('Comino', 'comino', 'Condimentos y edulcorantes'),
  ('Canela en polvo', 'canela en polvo', 'Condimentos y edulcorantes'),
  ('Pasta de pimiento choricero', 'pasta de pimiento choricero', 'Condimentos y edulcorantes'),
  ('Anis estrellado', 'anis estrellado', 'Condimentos y edulcorantes'),
  ('Aceituna verde', 'aceituna verde', 'Conservas y otros'),
  ('Aceituna negra', 'aceituna negra', 'Conservas y otros'),
  ('Anchoa en conserva', 'anchoa en conserva', 'Conservas y otros'),
  ('Atún en conserva', 'atun en conserva', 'Conservas y otros'),
  ('Sardina en conserva', 'sardina en conserva', 'Conservas y otros'),
  ('Mejillón en escabeche', 'mejillon en escabeche', 'Conservas y otros'),
  ('Berberecho al natural', 'berberecho al natural', 'Conservas y otros'),
  ('Espárrago blanco', 'esparrago blanco', 'Conservas y otros'),
  ('Pimiento del piquillo', 'pimiento del piquillo', 'Conservas y otros'),
  ('Tomate triturado', 'tomate triturado', 'Conservas y otros'),
  ('Tomate frito', 'tomate frito', 'Conservas y otros'),
  ('Concentrado de tomate', 'concentrado de tomate', 'Conservas y otros'),
  ('Garbanzo cocido', 'garbanzo cocido', 'Conservas y otros'),
  ('Lenteja cocida', 'lenteja cocida', 'Conservas y otros'),
  ('Alubia blanca cocida', 'alubia blanca cocida', 'Conservas y otros'),
  ('Caldo de pollo', 'caldo de pollo', 'Conservas y otros'),
  ('Caldo de pescado', 'caldo de pescado', 'Conservas y otros'),
  ('Fondo de carne', 'fondo de carne', 'Conservas y otros'),
  ('Sal de mesa', 'sal de mesa', 'Conservas y otros')
on conflict (normalized_name) do nothing;
