-- Defaults de stock mínimo por ingrediente del catálogo: unidad de referencia + mínimo.
-- Se pre-rellenan al añadir el ingrediente desde el catálogo (ver 0020_min_stock).
update ingredients as i set
  default_unit = v.unit,
  default_min_stock = v.min
from (values
  ('aceite de ajo', 'botella', 1),
  ('aceite de girasol', 'botella', 1),
  ('aceite de oliva', 'botella', 1),
  ('aceite de oliva suave', 'botella', 1),
  ('aceite de oliva virgen extra', 'botella', 1),
  ('aceite de sesamo', 'botella', 1),
  ('aceite de trufa', 'botella', 1),
  ('aceituna negra', 'bote', 1),
  ('aceituna verde', 'bote', 1),
  ('acelga', 'ramillete', 1),
  ('agar-agar en polvo', 'g', 10),
  ('agua', 'l', 1),
  ('agua o caldo vegetal', 'l', 1),
  ('agua para el caramelo', 'ml', 100),
  ('aguacate', 'ud', 2),
  ('aguacate maduro', 'ud', 2),
  ('aguacates maduros', 'ud', 2),
  ('ajo', 'cabeza', 1),
  ('ajo blanco', 'cabeza', 1),
  ('ajo morado', 'cabeza', 1),
  ('albahaca', 'ramillete', 1),
  ('albaricoque', 'ud', 3),
  ('alcachofa', 'ud', 3),
  ('alcachofas frescas', 'ud', 3),
  ('alita de pollo', 'ud', 6),
  ('almeja babosa', 'g', 300),
  ('almeja fina', 'g', 300),
  ('almendra cruda', 'g', 100),
  ('almendra laminada', 'g', 50),
  ('almendra largueta', 'g', 100),
  ('almendra marcona', 'g', 100),
  ('almendra tostada', 'g', 100),
  ('altramuz', 'g', 500),
  ('alubia arrocina', 'g', 500),
  ('alubia blanca alubion', 'g', 500),
  ('alubia blanca cocida', 'bote', 1),
  ('alubia blanca plancheta', 'g', 500),
  ('alubia blanca rinon', 'g', 500),
  ('alubia carilla', 'g', 500),
  ('alubia ganxet', 'g', 500),
  ('alubia negra', 'g', 500),
  ('alubia pinta', 'g', 500),
  ('alubia pocha', 'g', 500),
  ('alubia roja', 'g', 250),
  ('alubia roja de tolosa', 'g', 500),
  ('alubia verdina', 'g', 500),
  ('anacardo', 'g', 100),
  ('anchoa', 'lata', 1),
  ('anchoa en conserva', 'lata', 1),
  ('anis en grano', 'g', 15),
  ('anis estrellado', 'g', 15),
  ('apio', 'ud', 2),
  ('arroz', 'g', 250),
  ('arroz arborio', 'g', 250),
  ('arroz basmati', 'g', 500),
  ('arroz bomba', 'g', 500),
  ('arroz integral', 'g', 500),
  ('arroz redondo', 'g', 500),
  ('arroz redondo (tipo bomba)', 'g', 250),
  ('atun en conserva', 'lata', 1),
  ('atun rojo', 'g', 250),
  ('avellana', 'g', 100),
  ('avellana tostada', 'g', 100),
  ('avena en copos', 'g', 500),
  ('azafran', 'bote', 1),
  ('azafran en hebra', 'bote', 1),
  ('azucar', 'g', 250),
  ('azucar blanca', 'g', 250),
  ('azucar blanco', 'g', 250),
  ('azucar moreno', 'g', 250),
  ('azucar para el caramelo', 'g', 100),
  ('bacalao desalado', 'g', 300),
  ('bacalao fresco', 'g', 300),
  ('bacon de pavo', 'paquete', 1),
  ('berberecho', 'g', 250),
  ('berberecho al natural', 'lata', 1),
  ('berenjena', 'ud', 2),
  ('bogavante', 'g', 400),
  ('bonito del norte', 'lata', 1),
  ('boqueron', 'g', 250),
  ('breva', 'ud', 3),
  ('brocoli', 'ud', 2),
  ('bulgur', 'g', 500),
  ('caballa', 'g', 300),
  ('cacahuete', 'g', 100),
  ('cacahuete tostado', 'g', 100),
  ('calabacin', 'ud', 2),
  ('calabaza', 'g', 300),
  ('calabaza pelada y cortada en cubos', 'g', 250),
  ('calamar', 'g', 300),
  ('caldo de pescado', 'brick', 1),
  ('caldo de pollo', 'brick', 1),
  ('caldo de verduras', 'brick', 1),
  ('callos de ternera', 'g', 300),
  ('canela en polvo', 'g', 15),
  ('canela en rama', 'g', 15),
  ('cardo', 'g', 200),
  ('carne de cerdo', 'g', 250),
  ('carne picada de ternera', 'g', 250),
  ('castana', 'g', 100),
  ('castana pilonga', 'g', 100),
  ('cebada perlada', 'g', 500),
  ('cebolla', 'ud', 3),
  ('cebolla blanca', 'ud', 3),
  ('cebolla morada', 'ud', 2),
  ('cebolla morada picada', 'ud', 2),
  ('cebolleta', 'ud', 3),
  ('cebollino', 'ramillete', 1),
  ('cereza', 'g', 150),
  ('champinon', 'g', 150),
  ('chocolate negro', 'g', 100),
  ('chorizo fresco', 'g', 200),
  ('chuletilla de cordero', 'ud', 4),
  ('chuleton de ternera', 'g', 300),
  ('cigala', 'g', 250),
  ('cilantro', 'ramillete', 1),
  ('ciruela claudia', 'ud', 3),
  ('ciruela roja', 'ud', 3),
  ('clara de huevo', 'ud', 4),
  ('clavo', 'g', 15),
  ('codorniz', 'ud', 2),
  ('coliflor', 'ud', 2),
  ('comino', 'g', 15),
  ('comino en polvo', 'g', 15),
  ('comino molido', 'g', 15),
  ('concentrado de tomate', 'lata', 1),
  ('conejo de campo', 'ud', 1),
  ('cordero lechal', 'g', 500),
  ('costilla de cerdo', 'g', 300),
  ('cuajada', 'ud', 2),
  ('curcuma', 'g', 15),
  ('curry en polvo', 'g', 15),
  ('cuscus', 'g', 500),
  ('diente de ajo', 'cabeza', 1),
  ('dientes de ajo', 'cabeza', 1),
  ('dientes de ajo picados', 'cabeza', 1),
  ('dorada', 'g', 300),
  ('eneldo', 'g', 10),
  ('esencia de vainilla', 'botella', 1),
  ('espagueti', 'paquete', 1),
  ('esparrago blanco', 'bote', 1),
  ('esparrago triguero', 'ramillete', 1),
  ('espinaca', 'g', 200),
  ('fideo cabellin', 'g', 250),
  ('fideo de arroz', 'paquete', 1),
  ('fideo ramen', 'paquete', 1),
  ('fondo de carne', 'brick', 1),
  ('fresa', 'g', 150),
  ('freson', 'g', 150),
  ('gamba', 'g', 250),
  ('gamba blanca', 'g', 250),
  ('gamba roja', 'g', 250),
  ('gambon', 'g', 250),
  ('garbanzo castellano', 'g', 500),
  ('garbanzo cocido', 'bote', 1),
  ('garbanzo garbanzuelo', 'g', 500),
  ('garbanzo lechoso', 'g', 500),
  ('garbanzo pedrosillano', 'g', 500),
  ('garbanzo seco', 'g', 250),
  ('garbanzo tolosano', 'g', 500),
  ('garrofon', 'g', 200),
  ('gochujang', 'bote', 1),
  ('granada', 'ud', 2),
  ('guindilla', 'g', 15),
  ('guisante', 'g', 200),
  ('guisante partido', 'g', 500),
  ('guisante seco', 'g', 500),
  ('haba', 'g', 200),
  ('haba baby', 'g', 500),
  ('haba seca', 'g', 500),
  ('habas frescas', 'g', 500),
  ('harina', 'g', 250),
  ('harina de fuerza', 'g', 500),
  ('harina de maiz', 'g', 500),
  ('harina de trigo', 'g', 500),
  ('hebras de azafran', 'g', 10),
  ('hierbabuena', 'ramillete', 1),
  ('higo', 'ud', 3),
  ('huevo', 'ud', 6),
  ('huevo de codorniz', 'ud', 6),
  ('huevo de gallina', 'ud', 6),
  ('huevos camperos', 'ud', 6),
  ('huevos grandes', 'ud', 6),
  ('huevos l', 'ud', 6),
  ('jamon de pavo', 'paquete', 1),
  ('jamon iberico', 'paquete', 1),
  ('jamon serrano', 'paquete', 1),
  ('jamon serrano en lonchas', 'loncha', 4),
  ('jamon serrano en lonchas finas', 'loncha', 4),
  ('jamon serrano en taquitos', 'paquete', 1),
  ('jengibre', 'g', 50),
  ('judia verde plana', 'g', 200),
  ('judia verde redonda', 'g', 200),
  ('judias verdes planas (bachoqueta)', 'g', 250),
  ('judion de la granja', 'g', 500),
  ('lacon', 'g', 200),
  ('langosta', 'g', 400),
  ('langostino', 'g', 250),
  ('laurel', 'g', 10),
  ('laurel seco', 'g', 10),
  ('leche', 'l', 1),
  ('leche condensada', 'bote', 1),
  ('leche de coco', 'lata', 1),
  ('leche de coco de lata', 'lata', 1),
  ('leche desnatada', 'brick', 1),
  ('leche entera', 'brick', 1),
  ('leche evaporada', 'lata', 1),
  ('leche semidesnatada', 'brick', 1),
  ('lechuga hoja de roble', 'ud', 2),
  ('lechuga romana', 'ud', 2),
  ('lenguado', 'g', 300),
  ('lenteja', 'g', 250),
  ('lenteja beluga', 'g', 250),
  ('lenteja castellana', 'g', 250),
  ('lenteja caviar', 'g', 250),
  ('lenteja cocida', 'bote', 1),
  ('lenteja pardina', 'g', 250),
  ('lenteja roja', 'g', 250),
  ('lenteja rubia', 'g', 250),
  ('lenteja verdina', 'g', 250),
  ('lentejas pardina', 'g', 250),
  ('levadura quimica', 'g', 15),
  ('lima', 'ud', 2),
  ('limon', 'ud', 3),
  ('limon amarillo', 'ud', 2),
  ('lomo de cerdo', 'g', 300),
  ('longaniza', 'g', 200),
  ('lubina', 'g', 300),
  ('magro de cerdo', 'g', 250),
  ('maiz en grano', 'lata', 1),
  ('mandarina clementina', 'ud', 3),
  ('mantequilla', 'g', 100),
  ('mantequilla con sal', 'g', 100),
  ('mantequilla sin sal', 'g', 100),
  ('manzana golden', 'ud', 3),
  ('manzana granny smith', 'ud', 3),
  ('masa de pizza', 'ud', 1),
  ('mayonesa', 'bote', 1),
  ('mejillon', 'g', 300),
  ('mejillon en escabeche', 'lata', 1),
  ('melocoton amarillo', 'ud', 2),
  ('melocoton paraguayo', 'ud', 2),
  ('melon piel de sapo', 'ud', 1),
  ('membrillo', 'ud', 2),
  ('menta', 'ramillete', 1),
  ('merluza', 'g', 300),
  ('miel de milflores', 'bote', 1),
  ('miel de romero', 'bote', 1),
  ('mijo', 'g', 500),
  ('morcilla de arroz', 'ud', 2),
  ('morcilla de cebolla', 'ud', 2),
  ('mostaza antigua', 'bote', 1),
  ('mostaza de dijon', 'bote', 1),
  ('mozzarella', 'g', 125),
  ('muslo de pollo', 'ud', 4),
  ('naranja de mesa', 'ud', 3),
  ('naranja de zumo', 'ud', 3),
  ('nata para cocinar', 'brick', 1),
  ('nata para montar', 'brick', 1),
  ('navaja', 'g', 250),
  ('nectarina', 'ud', 2),
  ('nora', 'g', 15),
  ('nuez', 'g', 100),
  ('nuez de macadamia', 'g', 100),
  ('nuez moscada', 'g', 10),
  ('nuez pecana', 'g', 100),
  ('oregano', 'g', 15),
  ('oregano seco', 'g', 15),
  ('paletilla de cordero', 'ud', 1),
  ('pan', 'ud', 1),
  ('pan de barra', 'ud', 1),
  ('pan de centeno', 'ud', 1),
  ('pan de hogaza', 'ud', 1),
  ('pan de molde', 'paquete', 1),
  ('pan integral', 'ud', 1),
  ('pan rallado', 'g', 250),
  ('panceta', 'g', 200),
  ('panceta de cerdo', 'g', 200),
  ('pasta de miso', 'bote', 1),
  ('pasta de pimiento choricero', 'bote', 1),
  ('pasta de sopa', 'g', 250),
  ('pasta espagueti', 'g', 500),
  ('pasta lasana', 'paquete', 1),
  ('pasta macarron', 'g', 500),
  ('pasta tallarines', 'g', 500),
  ('patata', 'g', 500),
  ('patatas medianas', 'ud', 3),
  ('pechuga de pollo', 'g', 300),
  ('pepino', 'ud', 2),
  ('pera conferencia', 'ud', 3),
  ('pera ercolina', 'ud', 3),
  ('perejil', 'ramillete', 1),
  ('perejil plano', 'ramillete', 1),
  ('picos de pan', 'paquete', 1),
  ('picota', 'g', 150),
  ('pimenton', 'g', 15),
  ('pimenton ahumado', 'g', 15),
  ('pimenton dulce', 'g', 15),
  ('pimenton picante', 'g', 15),
  ('pimienta blanca', 'g', 15),
  ('pimienta de cayena', 'g', 15),
  ('pimienta negra', 'g', 15),
  ('pimiento del piquillo', 'bote', 1),
  ('pimiento rojo', 'ud', 2),
  ('pimiento verde', 'ud', 2),
  ('pina', 'ud', 1),
  ('pinon', 'g', 50),
  ('pipa de calabaza tostada', 'g', 50),
  ('pipa de girasol', 'g', 50),
  ('pipa de girasol tostada', 'g', 50),
  ('pistacho', 'g', 100),
  ('pistacho pelado', 'g', 100),
  ('platano de canarias', 'ud', 3),
  ('pluma iberica', 'g', 250),
  ('pollo entero', 'ud', 1),
  ('presa iberica', 'g', 250),
  ('puerro', 'ud', 2),
  ('pulpo', 'g', 300),
  ('queso burgos', 'g', 150),
  ('queso crema', 'g', 150),
  ('queso de cabrales', 'g', 150),
  ('queso emmental', 'g', 150),
  ('queso fresco', 'g', 150),
  ('queso idiazabal', 'g', 150),
  ('queso mahon', 'g', 150),
  ('queso manchego curado', 'g', 150),
  ('queso manchego semicurado', 'g', 150),
  ('queso mozzarella', 'g', 150),
  ('queso parmesano', 'g', 100),
  ('queso pecorino', 'g', 100),
  ('queso rulo de cabra', 'g', 150),
  ('queso tetilla', 'g', 150),
  ('quinoa', 'g', 500),
  ('rabito de ternera', 'g', 300),
  ('rape', 'g', 300),
  ('ras el hanout', 'g', 15),
  ('reduccion de vinagre balsamico', 'botella', 1),
  ('requeson', 'g', 150),
  ('rodaballo', 'g', 300),
  ('romero', 'g', 15),
  ('romero fresco', 'ramillete', 1),
  ('rosquilletas', 'paquete', 1),
  ('sal', 'g', 250),
  ('sal de mesa', 'g', 500),
  ('sal fina', 'g', 250),
  ('sal gorda', 'g', 20),
  ('sal marina', 'g', 20),
  ('sal y pimienta', 'g', 100),
  ('sal y pimienta negra', 'g', 100),
  ('salchicha fresca', 'ud', 4),
  ('salmon', 'g', 250),
  ('salsa agridulce', 'bote', 1),
  ('salsa alioli', 'bote', 1),
  ('salsa barbacoa', 'botella', 1),
  ('salsa brava', 'bote', 1),
  ('salsa de pescado', 'botella', 1),
  ('salsa de soja', 'botella', 1),
  ('salsa de tomate frito', 'brick', 1),
  ('salsa de tomate triturado', 'brick', 1),
  ('salsa perrins', 'botella', 1),
  ('salsa pesto', 'bote', 1),
  ('salsa picante', 'botella', 1),
  ('salsa romesco', 'bote', 1),
  ('salsa tabasco', 'botella', 1),
  ('salsa vizcaina', 'bote', 1),
  ('sandia', 'ud', 1),
  ('sardina', 'g', 250),
  ('sardina en conserva', 'lata', 1),
  ('secreto iberico', 'g', 250),
  ('semilla de amapola', 'g', 50),
  ('semilla de calabaza', 'g', 50),
  ('semilla de chia', 'g', 50),
  ('semilla de lino', 'g', 50),
  ('semilla de lino dorado', 'g', 50),
  ('semilla de lino marron', 'g', 50),
  ('sepia', 'g', 300),
  ('sesamo', 'g', 50),
  ('sesamo blanco', 'g', 50),
  ('sesamo negro', 'g', 50),
  ('sesamo tostado', 'g', 50),
  ('seta', 'g', 250),
  ('setas ostra', 'g', 150),
  ('soja verde', 'g', 250),
  ('solomillo de cerdo', 'g', 250),
  ('solomillo de ternera', 'g', 250),
  ('tahini', 'bote', 1),
  ('tocino iberico', 'g', 200),
  ('tomate', 'ud', 3),
  ('tomate frito', 'brick', 1),
  ('tomate maduro', 'ud', 3),
  ('tomate maduro rallado', 'ud', 3),
  ('tomate pera', 'ud', 3),
  ('tomate rama', 'ud', 3),
  ('tomate triturado', 'lata', 1),
  ('tomillo', 'g', 15),
  ('tomillo fresco', 'ramillete', 1),
  ('tortilla de maiz', 'paquete', 1),
  ('tortitas de arroz', 'paquete', 1),
  ('trigo sarraceno', 'g', 500),
  ('uva blanca', 'g', 150),
  ('uva tinta', 'g', 150),
  ('vieira', 'g', 200),
  ('vinagre de arroz', 'botella', 1),
  ('vinagre de jerez', 'botella', 1),
  ('vinagre de manzana', 'botella', 1),
  ('vinagre de modena', 'botella', 1),
  ('vinagre de sidra', 'botella', 1),
  ('vinagre de vino', 'botella', 1),
  ('vinagre de vino blanco', 'botella', 1),
  ('vinagre de vino tinto', 'botella', 1),
  ('yema de huevo', 'ud', 4),
  ('yogur griego', 'ud', 4),
  ('yogur natural', 'ud', 4),
  ('zanahoria', 'ud', 3),
  ('zumo de lima', 'ml', 50),
  ('zumo de limon', 'ml', 50),
  ('zumo de naranja', 'ml', 200)
) as v(normalized_name, unit, min)
where i.normalized_name = v.normalized_name;
