-- Generado por scripts/generate-expiration-state-migration.mjs.
-- dataset-sha256: a6a4091c88cbe851c17d0b491d968f3e03c62be247bb48a474fa8aa8649e5662

create table public.expiration_profiles (
  id text primary key,
  min_days integer,
  max_days integer,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  priority_eligible boolean not null,
  source_id text not null,
  source_ref text not null,
  check (
    (
      min_days is not null
      and max_days is not null
      and min_days > 0
      and max_days > 0
      and min_days <= max_days
    )
    or (min_days is null and max_days is null and priority_eligible = false)
  )
);

create table public.ingredient_expiration_profiles (
  ingredient_id uuid primary key references public.ingredients (id) on delete cascade,
  profile_id text not null references public.expiration_profiles (id) on delete restrict,
  match_type text not null check (match_type in ('direct', 'family', 'fallback'))
);

insert into public.expiration_profiles (
  id, min_days, max_days, confidence, priority_eligible, source_id, source_ref
) values
  ('fruit-apple', 28, 42, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 248: Manzanas; rango refrigerado'),
  ('fruit-pear-stone', 3, 5, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 266: Melocotones, Nectarinas, Ciruelas, Peras, Zapote'),
  ('fruit-banana', 3, 5, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 268: Plátano; rango refrigerado tras madurar'),
  ('fruit-citrus', 10, 21, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 256: Frutas cítricas'),
  ('fruit-grape', 7, 7, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 261: Uvas'),
  ('fruit-berries', 2, 3, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 481: fresas, fresón, frutilla'),
  ('fruit-large-melon', 3, 4, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 495, 497: Sandía y melón de pulpa verde'),
  ('fruit-cherry', 2, 7, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 252, 483: Cerezas'),
  ('fruit-delicate', 2, 5, 'low', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 18: Frutas frescas delicadas; fallback conservador'),
  ('fruit-pomegranate', 30, 90, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 269: Granada'),
  ('fruit-firm', 14, 30, 'low', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 18: Frutas frescas firmes; fallback conservador'),
  ('fruit-pineapple', 5, 7, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 267: Piña madura'),
  ('fruit-avocado', 3, 4, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 250: Aguacates; tras madurar'),
  ('vegetable-potato', 30, 60, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 297: Papas'),
  ('vegetable-onion', 30, 30, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 294: Cebolla seca; rango de despensa'),
  ('vegetable-garlic', 30, 30, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 285: Ajo, bulbos sin romper'),
  ('vegetable-tomato', 5, 10, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 306, 600: Tomates'),
  ('vegetable-pepper', 4, 14, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 296: Pimientos'),
  ('vegetable-summer-squash', 4, 7, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 19: Vegetales frescos; calabacín y berenjena'),
  ('vegetable-root', 14, 21, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 279: Zanahorias, chirivía'),
  ('vegetable-green-bean', 3, 5, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 273: Frijoles y guisantes frescos'),
  ('vegetable-asparagus', 3, 4, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 271: Espárragos'),
  ('vegetable-artichoke', 7, 14, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 270: Alcachofas completas'),
  ('vegetable-leafy', 3, 7, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 291: Lechuga de hoja, espinacas'),
  ('vegetable-crucifer', 3, 5, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 276: Brócoli y grelo; familia crucíferas'),
  ('vegetable-pumpkin', 60, 90, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 298: Calabaza'),
  ('vegetable-cucumber', 4, 6, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 283: Pepinos'),
  ('vegetable-lettuce', 7, 14, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 290: Lechuga común y romana'),
  ('vegetable-allium-green', 7, 14, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 295: cebollas verdes o cebollines'),
  ('vegetable-celery', 7, 14, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 19: Vegetales frescos; apio'),
  ('vegetable-mushroom', 3, 7, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 19: Vegetales frescos; hongos'),
  ('meat-red-fresh', 3, 5, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 34-41, 44-51, 60-69: cortes frescos de res, cordero y cerdo'),
  ('meat-poultry-fresh', 1, 2, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 113, 116-118: pollo entero y partes'),
  ('meat-rabbit-fresh', 2, 2, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 595: Conejo entero, fresco'),
  ('meat-sausage-fresh', 1, 2, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: raw sausage, 1-2 days refrigerated'),
  ('meat-offal', 1, 2, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: variety meats, 1-2 days refrigerated'),
  ('meat-bacon', 7, 7, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: bacon, 1 week refrigerated'),
  ('meat-cured-sausage', 14, 21, 'medium', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: hard sausage such as pepperoni, opened package 2-3 weeks refrigerated'),
  ('meat-cured-ham', 60, 90, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: prosciutto or Serrano ham cut, 2-3 months refrigerated'),
  ('meat-cured-short', 5, 7, 'medium', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: refrigerated cured meat; conservative family range'),
  ('fish-lean', 1, 2, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 144-145: Pescado magro'),
  ('fish-fatty', 1, 2, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 146: Pescado graso'),
  ('fish-desalted', 2, 3, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 20: pescado fresco; bacalao desalado'),
  ('shellfish-crustacean', 3, 5, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: Shrimp, Crayfish'),
  ('shellfish-live', 5, 10, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: live clams, mussels, oysters and scallops'),
  ('shellfish-lobster', 1, 2, 'medium', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: live lobster'),
  ('seafood-cephalopod', 1, 3, 'high', true, 'foodsafety-cold-storage', 'FoodSafety.gov Cold Food Storage Chart: squid; familia cefalópodos'),
  ('dairy-milk', 7, 10, 'low', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 27: Leche (fecha de uso); fallback numérico de familia'),
  ('dairy-cream', 3, 10, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 13-15: Crema'),
  ('dairy-butter', 30, 60, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 1: Mantequilla'),
  ('cheese-hard', 180, 180, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 3: Quesos duros'),
  ('cheese-semi-hard', 21, 28, 'low', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 3: queso duro después de abrir (3-4 semanas), fallback conservador para semiduros'),
  ('cheese-soft', 7, 14, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 7: quesos suaves como brie y cabra'),
  ('cheese-fresh', 7, 14, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 7, 9: quesos suaves y requesón'),
  ('cheese-cream', 14, 14, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 10: Queso crema'),
  ('dairy-yogurt', 7, 14, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 33: Yogur'),
  ('egg-shell', 21, 35, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 21: Huevos en el cascarón'),
  ('egg-raw-parts', 2, 4, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 22: Yemas de huevo crudo; claras y yemas'),
  ('milk-canned', 365, 365, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 383: Leche evaporada o condensada enlatada'),
  ('dairy-curd', 7, 14, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 9, 33: lácteos frescos fermentados'),
  ('grain-rice-white', 730, 730, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 338: Arroz blanco o mixto'),
  ('grain-rice-brown', 365, 365, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 339: Arroz marrón'),
  ('bread-fresh', 3, 7, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 195, 451: productos de pan y panes caseros'),
  ('bread-packaged', 14, 18, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 195: Productos de pan comerciales'),
  ('pasta-dry', 730, 730, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 335: Pasta seca sin huevo'),
  ('grain-dry', 365, 730, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 9: granos secos'),
  ('flour-white', 180, 365, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 222: Harina blanca'),
  ('flour-corn', 180, 365, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 218: Harina de maíz'),
  ('bread-dry', 180, 365, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 23: pan rallado y productos secos de pan'),
  ('legume-dry', 365, 730, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 333: Frijoles secos'),
  ('legume-fresh', 3, 5, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 273: Frijoles y guisantes frescos'),
  ('nuts-raw', 90, 180, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 23: frutos secos; rango conservador de calidad'),
  ('seeds-general', 180, 365, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 604-608: semillas de calabaza y girasol'),
  ('seeds-long', 548, 730, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 503, 573: linaza y chía'),
  ('chestnut-fresh', 7, 14, 'low', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 18/23: castaña fresca; fallback conservador'),
  ('herb-fresh', 7, 10, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 288: Hierbas frescas'),
  ('herb-dry', 365, 730, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 236: Hierbas secas'),
  ('spice-ground', 730, 1095, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 238: Especias molidas'),
  ('spice-whole', 1095, 1460, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 237: Especias completas'),
  ('salt-indefinite', null, null, 'high', false, 'foodkeeper-es', 'FoodKeeper ES v128 Product 468: Sal; indefinidamente'),
  ('sugar-long', 730, 730, 'high', false, 'foodkeeper-es', 'FoodKeeper ES v128 Products 239-241: Azúcar; recomendación de calidad de 2 años'),
  ('honey-long', 730, 730, 'high', false, 'foodkeeper-es', 'FoodKeeper ES v128 Product 345: Miel'),
  ('oil-general', 180, 365, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 227: Aceites de oliva y vegetal'),
  ('oil-nut-seed', 180, 365, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 228, 522: aceites de nueces y girasol'),
  ('vinegar-long', 730, 1825, 'high', false, 'foodkeeper-es', 'FoodKeeper ES v128 Products 361, 669: Vinagre y vinagre balsámico'),
  ('sauce-tomato-shelf', 365, 548, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 373: productos enlatados altos en ácido'),
  ('sauce-refrigerated', 7, 14, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 6: salsas refrigeradas; familia'),
  ('sauce-aioli', 3, 4, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 670: Alioli hecho en casa; rango refrigerado'),
  ('sauce-pesto', 3, 3, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 354: Pesto envasado; rango conservador después de abrir'),
  ('garlic-oil-refrigerated', 1, 7, 'high', true, 'fsis-garlic-oil', 'USDA FSIS Garlic in Oil: fresco, refrigerado a 4 °C o menos, máximo 7 días'),
  ('sauce-shelf', 180, 365, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 340-351: salsas y condimentos envasados'),
  ('soy-sauce', 730, 730, 'medium', true, 'foodkeeper-es', 'FoodKeeper ES v128 Category 6: salsa de soja envasada'),
  ('mayonnaise', 90, 180, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 350: Mayonesa comercial'),
  ('mustard', 365, 730, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 351: Mostaza'),
  ('canned-low-acid', 730, 1825, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 372: Productos enlatados bajos en ácido'),
  ('canned-high-acid', 365, 548, 'high', true, 'foodkeeper-es', 'FoodKeeper ES v128 Product 373: Productos enlatados altos en ácido'),
  ('broth-shelf', 3, 4, 'low', true, 'foodkeeper-es', 'FoodKeeper ES v128 Products 485-486: caldos comerciales; rango conservador después de abrir');

with mappings (normalized_name, profile_id, match_type) as (
  values
    ('manzana golden', 'fruit-apple', 'direct'),
    ('manzana granny smith', 'fruit-apple', 'direct'),
    ('pera conferencia', 'fruit-pear-stone', 'family'),
    ('pera ercolina', 'fruit-pear-stone', 'family'),
    ('platano de canarias', 'fruit-banana', 'direct'),
    ('naranja de mesa', 'fruit-citrus', 'direct'),
    ('naranja de zumo', 'fruit-citrus', 'direct'),
    ('mandarina clementina', 'fruit-citrus', 'direct'),
    ('limon amarillo', 'fruit-citrus', 'direct'),
    ('lima', 'fruit-citrus', 'direct'),
    ('uva blanca', 'fruit-grape', 'direct'),
    ('uva tinta', 'fruit-grape', 'direct'),
    ('melocoton amarillo', 'fruit-pear-stone', 'family'),
    ('melocoton paraguayo', 'fruit-pear-stone', 'family'),
    ('nectarina', 'fruit-pear-stone', 'family'),
    ('albaricoque', 'fruit-pear-stone', 'family'),
    ('ciruela claudia', 'fruit-pear-stone', 'family'),
    ('ciruela roja', 'fruit-pear-stone', 'family'),
    ('cereza', 'fruit-cherry', 'direct'),
    ('picota', 'fruit-cherry', 'direct'),
    ('fresa', 'fruit-berries', 'direct'),
    ('freson', 'fruit-berries', 'direct'),
    ('melon piel de sapo', 'fruit-large-melon', 'direct'),
    ('sandia', 'fruit-large-melon', 'direct'),
    ('higo', 'fruit-delicate', 'fallback'),
    ('breva', 'fruit-delicate', 'fallback'),
    ('granada', 'fruit-pomegranate', 'direct'),
    ('membrillo', 'fruit-firm', 'fallback'),
    ('pina', 'fruit-pineapple', 'direct'),
    ('aguacate', 'fruit-avocado', 'direct'),
    ('patata', 'vegetable-potato', 'direct'),
    ('cebolla blanca', 'vegetable-onion', 'direct'),
    ('cebolla morada', 'vegetable-onion', 'direct'),
    ('ajo', 'vegetable-garlic', 'family'),
    ('tomate pera', 'vegetable-tomato', 'family'),
    ('tomate rama', 'vegetable-tomato', 'family'),
    ('pimiento verde', 'vegetable-pepper', 'family'),
    ('pimiento rojo', 'vegetable-pepper', 'family'),
    ('calabacin', 'vegetable-summer-squash', 'family'),
    ('berenjena', 'vegetable-summer-squash', 'family'),
    ('zanahoria', 'vegetable-root', 'direct'),
    ('judia verde plana', 'vegetable-green-bean', 'family'),
    ('judia verde redonda', 'vegetable-green-bean', 'family'),
    ('esparrago triguero', 'vegetable-asparagus', 'family'),
    ('alcachofa', 'vegetable-artichoke', 'family'),
    ('espinaca', 'vegetable-leafy', 'family'),
    ('acelga', 'vegetable-leafy', 'family'),
    ('coliflor', 'vegetable-crucifer', 'direct'),
    ('brocoli', 'vegetable-crucifer', 'direct'),
    ('calabaza', 'vegetable-pumpkin', 'family'),
    ('pepino', 'vegetable-cucumber', 'family'),
    ('lechuga romana', 'vegetable-lettuce', 'direct'),
    ('lechuga hoja de roble', 'vegetable-lettuce', 'direct'),
    ('puerro', 'vegetable-allium-green', 'family'),
    ('apio', 'vegetable-celery', 'family'),
    ('guisante', 'vegetable-green-bean', 'family'),
    ('haba', 'vegetable-green-bean', 'family'),
    ('cardo', 'vegetable-artichoke', 'family'),
    ('champinon', 'vegetable-mushroom', 'family'),
    ('setas ostra', 'vegetable-mushroom', 'family'),
    ('solomillo de cerdo', 'meat-red-fresh', 'family'),
    ('lomo de cerdo', 'meat-red-fresh', 'family'),
    ('secreto iberico', 'meat-red-fresh', 'family'),
    ('presa iberica', 'meat-red-fresh', 'family'),
    ('pluma iberica', 'meat-red-fresh', 'family'),
    ('panceta de cerdo', 'meat-bacon', 'family'),
    ('costilla de cerdo', 'meat-red-fresh', 'family'),
    ('chorizo fresco', 'meat-sausage-fresh', 'family'),
    ('morcilla de arroz', 'meat-sausage-fresh', 'family'),
    ('morcilla de cebolla', 'meat-sausage-fresh', 'family'),
    ('jamon serrano', 'meat-cured-ham', 'family'),
    ('jamon iberico', 'meat-cured-ham', 'family'),
    ('chuleton de ternera', 'meat-red-fresh', 'family'),
    ('solomillo de ternera', 'meat-red-fresh', 'family'),
    ('rabito de ternera', 'meat-red-fresh', 'family'),
    ('callos de ternera', 'meat-offal', 'family'),
    ('pollo entero', 'meat-poultry-fresh', 'direct'),
    ('pechuga de pollo', 'meat-poultry-fresh', 'direct'),
    ('muslo de pollo', 'meat-poultry-fresh', 'direct'),
    ('alita de pollo', 'meat-poultry-fresh', 'direct'),
    ('conejo de campo', 'meat-rabbit-fresh', 'direct'),
    ('codorniz', 'meat-poultry-fresh', 'direct'),
    ('cordero lechal', 'meat-red-fresh', 'family'),
    ('chuletilla de cordero', 'meat-red-fresh', 'family'),
    ('paletilla de cordero', 'meat-red-fresh', 'family'),
    ('magro de cerdo', 'meat-red-fresh', 'family'),
    ('tocino iberico', 'meat-bacon', 'family'),
    ('salchicha fresca', 'meat-sausage-fresh', 'family'),
    ('longaniza', 'meat-sausage-fresh', 'family'),
    ('lacon', 'meat-cured-short', 'family'),
    ('merluza', 'fish-lean', 'direct'),
    ('bacalao fresco', 'fish-lean', 'direct'),
    ('bacalao desalado', 'fish-desalted', 'family'),
    ('rape', 'fish-lean', 'direct'),
    ('lenguado', 'fish-lean', 'direct'),
    ('dorada', 'fish-lean', 'direct'),
    ('lubina', 'fish-lean', 'direct'),
    ('rodaballo', 'fish-lean', 'direct'),
    ('atun rojo', 'fish-fatty', 'direct'),
    ('bonito del norte', 'fish-fatty', 'direct'),
    ('boqueron', 'fish-fatty', 'direct'),
    ('sardina', 'fish-fatty', 'direct'),
    ('caballa', 'fish-fatty', 'direct'),
    ('anchoa', 'fish-fatty', 'direct'),
    ('gambon', 'shellfish-crustacean', 'family'),
    ('gamba blanca', 'shellfish-crustacean', 'family'),
    ('gamba roja', 'shellfish-crustacean', 'family'),
    ('langostino', 'shellfish-crustacean', 'family'),
    ('cigala', 'shellfish-crustacean', 'family'),
    ('bogavante', 'shellfish-lobster', 'family'),
    ('langosta', 'shellfish-lobster', 'family'),
    ('mejillon', 'shellfish-live', 'family'),
    ('almeja babosa', 'shellfish-live', 'family'),
    ('almeja fina', 'shellfish-live', 'family'),
    ('berberecho', 'shellfish-live', 'family'),
    ('navaja', 'shellfish-live', 'family'),
    ('vieira', 'shellfish-live', 'family'),
    ('pulpo', 'seafood-cephalopod', 'family'),
    ('calamar', 'seafood-cephalopod', 'family'),
    ('sepia', 'seafood-cephalopod', 'family'),
    ('leche entera', 'dairy-milk', 'fallback'),
    ('leche semidesnatada', 'dairy-milk', 'fallback'),
    ('leche desnatada', 'dairy-milk', 'fallback'),
    ('nata para montar', 'dairy-cream', 'family'),
    ('nata para cocinar', 'dairy-cream', 'family'),
    ('mantequilla con sal', 'dairy-butter', 'direct'),
    ('mantequilla sin sal', 'dairy-butter', 'direct'),
    ('queso manchego semicurado', 'cheese-semi-hard', 'fallback'),
    ('queso manchego curado', 'cheese-hard', 'direct'),
    ('queso fresco', 'cheese-fresh', 'family'),
    ('queso de cabrales', 'cheese-soft', 'family'),
    ('queso tetilla', 'cheese-soft', 'family'),
    ('queso idiazabal', 'cheese-hard', 'direct'),
    ('queso mahon', 'cheese-semi-hard', 'fallback'),
    ('queso burgos', 'cheese-fresh', 'family'),
    ('requeson', 'cheese-fresh', 'family'),
    ('yogur natural', 'dairy-yogurt', 'direct'),
    ('yogur griego', 'dairy-yogurt', 'direct'),
    ('huevo de gallina', 'egg-shell', 'direct'),
    ('huevo de codorniz', 'egg-shell', 'direct'),
    ('clara de huevo', 'egg-raw-parts', 'direct'),
    ('yema de huevo', 'egg-raw-parts', 'direct'),
    ('queso rulo de cabra', 'cheese-fresh', 'family'),
    ('queso crema', 'cheese-cream', 'direct'),
    ('queso parmesano', 'cheese-hard', 'direct'),
    ('queso emmental', 'cheese-hard', 'direct'),
    ('queso mozzarella', 'cheese-soft', 'family'),
    ('leche evaporada', 'milk-canned', 'direct'),
    ('leche condensada', 'milk-canned', 'direct'),
    ('cuajada', 'dairy-curd', 'family'),
    ('arroz bomba', 'grain-rice-white', 'direct'),
    ('arroz basmati', 'grain-rice-white', 'direct'),
    ('arroz integral', 'grain-rice-brown', 'direct'),
    ('arroz redondo', 'grain-rice-white', 'direct'),
    ('pan de hogaza', 'bread-fresh', 'family'),
    ('pan de barra', 'bread-fresh', 'family'),
    ('pan integral', 'bread-fresh', 'family'),
    ('pan de centeno', 'bread-fresh', 'family'),
    ('pan de molde', 'bread-packaged', 'direct'),
    ('pasta espagueti', 'pasta-dry', 'direct'),
    ('pasta macarron', 'pasta-dry', 'direct'),
    ('pasta tallarines', 'pasta-dry', 'direct'),
    ('pasta de sopa', 'pasta-dry', 'direct'),
    ('pasta lasana', 'pasta-dry', 'direct'),
    ('avena en copos', 'grain-dry', 'family'),
    ('cebada perlada', 'grain-dry', 'family'),
    ('quinoa', 'grain-dry', 'family'),
    ('cuscus', 'grain-dry', 'family'),
    ('harina de trigo', 'flour-white', 'direct'),
    ('harina de fuerza', 'flour-white', 'direct'),
    ('harina de maiz', 'flour-corn', 'direct'),
    ('maiz en grano', 'grain-dry', 'family'),
    ('pan rallado', 'bread-dry', 'family'),
    ('picos de pan', 'bread-dry', 'family'),
    ('rosquilletas', 'bread-dry', 'family'),
    ('tortitas de arroz', 'bread-dry', 'family'),
    ('bulgur', 'grain-dry', 'family'),
    ('mijo', 'grain-dry', 'family'),
    ('trigo sarraceno', 'grain-dry', 'family'),
    ('fideo cabellin', 'pasta-dry', 'direct'),
    ('garbanzo castellano', 'legume-dry', 'direct'),
    ('garbanzo pedrosillano', 'legume-dry', 'direct'),
    ('garbanzo lechoso', 'legume-dry', 'direct'),
    ('lenteja pardina', 'legume-dry', 'direct'),
    ('lenteja verdina', 'legume-dry', 'direct'),
    ('lenteja castellana', 'legume-dry', 'direct'),
    ('lenteja caviar', 'legume-dry', 'direct'),
    ('alubia blanca rinon', 'legume-dry', 'direct'),
    ('alubia blanca plancheta', 'legume-dry', 'direct'),
    ('alubia blanca alubion', 'legume-dry', 'direct'),
    ('alubia pinta', 'legume-dry', 'direct'),
    ('alubia roja de tolosa', 'legume-dry', 'direct'),
    ('alubia carilla', 'legume-dry', 'direct'),
    ('alubia pocha', 'legume-fresh', 'direct'),
    ('alubia ganxet', 'legume-dry', 'direct'),
    ('habas frescas', 'legume-fresh', 'direct'),
    ('haba seca', 'legume-dry', 'direct'),
    ('soja verde', 'legume-dry', 'direct'),
    ('altramuz', 'legume-dry', 'direct'),
    ('guisante seco', 'legume-dry', 'direct'),
    ('guisante partido', 'legume-dry', 'direct'),
    ('garbanzo garbanzuelo', 'legume-dry', 'direct'),
    ('lenteja rubia', 'legume-dry', 'direct'),
    ('alubia arrocina', 'legume-dry', 'direct'),
    ('alubia verdina', 'legume-dry', 'direct'),
    ('haba baby', 'legume-fresh', 'direct'),
    ('lenteja beluga', 'legume-dry', 'direct'),
    ('garbanzo tolosano', 'legume-dry', 'direct'),
    ('alubia negra', 'legume-dry', 'direct'),
    ('judion de la granja', 'legume-dry', 'direct'),
    ('almendra cruda', 'nuts-raw', 'family'),
    ('almendra tostada', 'nuts-raw', 'family'),
    ('almendra laminada', 'nuts-raw', 'family'),
    ('avellana', 'nuts-raw', 'family'),
    ('nuez', 'nuts-raw', 'family'),
    ('pistacho', 'nuts-raw', 'family'),
    ('pinon', 'nuts-raw', 'family'),
    ('cacahuete', 'nuts-raw', 'family'),
    ('anacardo', 'nuts-raw', 'family'),
    ('nuez de macadamia', 'nuts-raw', 'family'),
    ('pipa de girasol', 'seeds-general', 'family'),
    ('semilla de calabaza', 'seeds-general', 'family'),
    ('sesamo blanco', 'seeds-general', 'family'),
    ('sesamo negro', 'seeds-general', 'family'),
    ('semilla de chia', 'seeds-long', 'family'),
    ('semilla de lino', 'seeds-long', 'family'),
    ('semilla de amapola', 'seeds-general', 'family'),
    ('castana', 'chestnut-fresh', 'fallback'),
    ('castana pilonga', 'nuts-raw', 'family'),
    ('nuez pecana', 'nuts-raw', 'family'),
    ('almendra marcona', 'nuts-raw', 'family'),
    ('almendra largueta', 'nuts-raw', 'family'),
    ('avellana tostada', 'nuts-raw', 'family'),
    ('pipa de girasol tostada', 'seeds-general', 'family'),
    ('pipa de calabaza tostada', 'seeds-general', 'family'),
    ('sesamo tostado', 'seeds-general', 'family'),
    ('semilla de lino dorado', 'seeds-long', 'family'),
    ('semilla de lino marron', 'seeds-long', 'family'),
    ('pistacho pelado', 'nuts-raw', 'family'),
    ('cacahuete tostado', 'nuts-raw', 'family'),
    ('azafran', 'spice-whole', 'direct'),
    ('pimenton dulce', 'spice-ground', 'direct'),
    ('pimenton picante', 'spice-ground', 'direct'),
    ('pimenton ahumado', 'spice-ground', 'direct'),
    ('oregano seco', 'herb-dry', 'direct'),
    ('tomillo fresco', 'herb-fresh', 'direct'),
    ('romero fresco', 'herb-fresh', 'direct'),
    ('perejil plano', 'herb-fresh', 'direct'),
    ('laurel seco', 'herb-dry', 'direct'),
    ('comino molido', 'spice-ground', 'direct'),
    ('clavo', 'spice-whole', 'direct'),
    ('canela en rama', 'spice-whole', 'direct'),
    ('nuez moscada', 'spice-whole', 'direct'),
    ('pimienta negra', 'spice-ground', 'direct'),
    ('pimienta blanca', 'spice-ground', 'direct'),
    ('pimienta de cayena', 'spice-ground', 'direct'),
    ('ajo morado', 'vegetable-garlic', 'family'),
    ('ajo blanco', 'vegetable-garlic', 'family'),
    ('cebollino', 'herb-fresh', 'direct'),
    ('menta', 'herb-fresh', 'direct'),
    ('hierbabuena', 'herb-fresh', 'direct'),
    ('albahaca', 'herb-fresh', 'direct'),
    ('anis en grano', 'spice-whole', 'direct'),
    ('cilantro', 'herb-fresh', 'direct'),
    ('sal marina', 'salt-indefinite', 'family'),
    ('sal gorda', 'salt-indefinite', 'family'),
    ('azafran en hebra', 'spice-whole', 'direct'),
    ('nora', 'spice-whole', 'direct'),
    ('aceite de oliva virgen extra', 'oil-general', 'direct'),
    ('aceite de oliva suave', 'oil-general', 'direct'),
    ('aceite de girasol', 'oil-general', 'direct'),
    ('vinagre de jerez', 'vinegar-long', 'direct'),
    ('vinagre de vino blanco', 'vinegar-long', 'direct'),
    ('vinagre de vino tinto', 'vinegar-long', 'direct'),
    ('vinagre de manzana', 'vinegar-long', 'direct'),
    ('vinagre de modena', 'vinegar-long', 'direct'),
    ('salsa de tomate frito', 'sauce-tomato-shelf', 'family'),
    ('salsa de tomate triturado', 'sauce-tomato-shelf', 'family'),
    ('salsa alioli', 'sauce-aioli', 'fallback'),
    ('salsa romesco', 'sauce-refrigerated', 'family'),
    ('salsa brava', 'sauce-refrigerated', 'family'),
    ('salsa vizcaina', 'sauce-refrigerated', 'family'),
    ('salsa de soja', 'soy-sauce', 'family'),
    ('mayonesa', 'mayonnaise', 'direct'),
    ('mostaza antigua', 'mustard', 'direct'),
    ('mostaza de dijon', 'mustard', 'direct'),
    ('salsa perrins', 'sauce-shelf', 'family'),
    ('salsa tabasco', 'sauce-shelf', 'family'),
    ('aceite de sesamo', 'oil-nut-seed', 'family'),
    ('vinagre de arroz', 'vinegar-long', 'direct'),
    ('salsa agridulce', 'sauce-shelf', 'family'),
    ('reduccion de vinagre balsamico', 'vinegar-long', 'direct'),
    ('aceite de trufa', 'oil-nut-seed', 'family'),
    ('salsa barbacoa', 'sauce-shelf', 'family'),
    ('salsa pesto', 'sauce-pesto', 'fallback'),
    ('aceite de ajo', 'garlic-oil-refrigerated', 'direct'),
    ('vinagre de sidra', 'vinegar-long', 'direct'),
    ('salsa picante', 'sauce-shelf', 'family'),
    ('sal fina', 'salt-indefinite', 'family'),
    ('azucar blanco', 'sugar-long', 'family'),
    ('azucar moreno', 'sugar-long', 'family'),
    ('miel de milflores', 'honey-long', 'family'),
    ('miel de romero', 'honey-long', 'family'),
    ('laurel', 'herb-dry', 'direct'),
    ('oregano', 'herb-dry', 'direct'),
    ('tomillo', 'herb-dry', 'direct'),
    ('romero', 'herb-dry', 'direct'),
    ('perejil', 'herb-dry', 'direct'),
    ('comino', 'spice-ground', 'direct'),
    ('canela en polvo', 'spice-ground', 'direct'),
    ('pasta de pimiento choricero', 'sauce-refrigerated', 'family'),
    ('anis estrellado', 'spice-whole', 'direct'),
    ('aceituna verde', 'canned-high-acid', 'direct'),
    ('aceituna negra', 'canned-high-acid', 'direct'),
    ('anchoa en conserva', 'canned-low-acid', 'direct'),
    ('atun en conserva', 'canned-low-acid', 'direct'),
    ('sardina en conserva', 'canned-low-acid', 'direct'),
    ('mejillon en escabeche', 'canned-low-acid', 'direct'),
    ('berberecho al natural', 'canned-low-acid', 'direct'),
    ('esparrago blanco', 'canned-high-acid', 'direct'),
    ('pimiento del piquillo', 'canned-high-acid', 'direct'),
    ('tomate triturado', 'canned-high-acid', 'direct'),
    ('tomate frito', 'canned-high-acid', 'direct'),
    ('concentrado de tomate', 'canned-high-acid', 'direct'),
    ('garbanzo cocido', 'canned-low-acid', 'direct'),
    ('lenteja cocida', 'canned-low-acid', 'direct'),
    ('alubia blanca cocida', 'canned-low-acid', 'direct'),
    ('caldo de pollo', 'broth-shelf', 'fallback'),
    ('caldo de pescado', 'broth-shelf', 'fallback'),
    ('fondo de carne', 'broth-shelf', 'fallback'),
    ('sal de mesa', 'salt-indefinite', 'family'),
    ('carne picada de pollo', 'meat-poultry-fresh', 'family'),
    ('carne picada mixta', 'meat-sausage-fresh', 'family'),
    ('contramuslo de pollo', 'meat-poultry-fresh', 'direct'),
    ('pechuga de pavo', 'meat-poultry-fresh', 'family'),
    ('carne picada de pavo', 'meat-poultry-fresh', 'family'),
    ('jamon cocido', 'meat-cured-short', 'family'),
    ('bacon', 'meat-bacon', 'direct'),
    ('chorizo curado', 'meat-cured-sausage', 'family'),
    ('higadito de pollo', 'meat-offal', 'family'),
    ('salmon', 'fish-fatty', 'direct'),
    ('salmon ahumado', 'fish-desalted', 'fallback'),
    ('trucha', 'fish-fatty', 'direct'),
    ('pez espada', 'fish-lean', 'family'),
    ('chipiron', 'seafood-cephalopod', 'family'),
    ('gulas', 'fish-desalted', 'fallback'),
    ('langostino cocido', 'shellfish-crustacean', 'family'),
    ('tomate cherry', 'vegetable-tomato', 'family'),
    ('rucula', 'vegetable-leafy', 'family'),
    ('canonigos', 'vegetable-leafy', 'family'),
    ('escarola', 'vegetable-lettuce', 'family'),
    ('endivia', 'vegetable-lettuce', 'family'),
    ('col lombarda', 'vegetable-lettuce', 'fallback'),
    ('coles de bruselas', 'vegetable-crucifer', 'family'),
    ('boniato', 'vegetable-potato', 'family'),
    ('pimiento amarillo', 'vegetable-pepper', 'direct'),
    ('seta shiitake', 'vegetable-mushroom', 'family'),
    ('champinon portobello', 'vegetable-mushroom', 'family'),
    ('kiwi', 'fruit-firm', 'family'),
    ('mango', 'fruit-delicate', 'family'),
    ('arandano', 'fruit-berries', 'family'),
    ('frambuesa', 'fruit-berries', 'family'),
    ('mora', 'fruit-berries', 'family'),
    ('pomelo', 'fruit-citrus', 'family'),
    ('datil', 'grain-dry', 'fallback'),
    ('ciruela pasa', 'grain-dry', 'fallback'),
    ('queso rallado', 'cheese-fresh', 'fallback'),
    ('queso feta', 'cheese-fresh', 'family'),
    ('queso mascarpone', 'cheese-fresh', 'family'),
    ('kefir', 'dairy-yogurt', 'family'),
    ('leche sin lactosa', 'dairy-milk', 'family'),
    ('bebida de avena', 'dairy-milk', 'fallback'),
    ('bebida de soja', 'dairy-milk', 'fallback'),
    ('bebida de almendra', 'dairy-milk', 'fallback'),
    ('maicena', 'flour-corn', 'family'),
    ('pasta fresca', 'bread-fresh', 'fallback'),
    ('noquis', 'bread-fresh', 'fallback'),
    ('pan de pita', 'bread-packaged', 'family'),
    ('tortilla de trigo', 'bread-packaged', 'family'),
    ('harina integral', 'flour-white', 'family'),
    ('galleta maria', 'bread-dry', 'family'),
    ('pepinillo en vinagre', 'canned-high-acid', 'family'),
    ('alcaparra', 'canned-high-acid', 'family'),
    ('maiz dulce en conserva', 'canned-low-acid', 'family'),
    ('pimiento asado', 'canned-low-acid', 'family'),
    ('alcachofa en conserva', 'canned-low-acid', 'family'),
    ('guisante en conserva', 'canned-low-acid', 'family'),
    ('aceite de coco', 'oil-general', 'family'),
    ('salsa sriracha', 'sauce-shelf', 'family'),
    ('salsa teriyaki', 'sauce-shelf', 'family'),
    ('salsa cesar', 'sauce-refrigerated', 'family'),
    ('ajo en polvo', 'spice-ground', 'family'),
    ('jengibre en polvo', 'spice-ground', 'family'),
    ('eneldo', 'herb-dry', 'family'),
    ('salvia', 'herb-dry', 'family'),
    ('estragon', 'herb-dry', 'family'),
    ('cacao en polvo', 'spice-ground', 'fallback'),
    ('azucar glas', 'sugar-long', 'family'),
    ('sirope de arce', 'honey-long', 'family')
)
insert into public.ingredient_expiration_profiles (ingredient_id, profile_id, match_type)
select i.id, m.profile_id, m.match_type
from mappings m
join public.ingredients i on i.normalized_name = m.normalized_name;

do $$
begin
  if (select count(*) from public.expiration_profiles) <> 97 then
    raise exception 'se esperaban 97 perfiles de caducidad';
  end if;
  if (select count(*) from public.ingredient_expiration_profiles) <> 399 then
    raise exception 'se esperaban 399 ingredientes con perfil';
  end if;
end;
$$;

alter table public.expiration_profiles enable row level security;
alter table public.ingredient_expiration_profiles enable row level security;

create policy "expiration_profiles_select_authenticated"
on public.expiration_profiles
for select to authenticated
using (true);

create policy "ingredient_expiration_profiles_select_authenticated"
on public.ingredient_expiration_profiles
for select to authenticated
using (true);

grant select on public.expiration_profiles, public.ingredient_expiration_profiles
to authenticated;

grant select, insert, update, delete
on public.expiration_profiles, public.ingredient_expiration_profiles
to service_role;
