-- Da de alta en bases ya migradas los 68 ingredientes que faltaban en el catálogo:
-- el seed 0007 y los datasets de caducidad y alérgenos ya los incluyen, pero esas migraciones
-- solo corren una vez, en una base nueva.
--
-- Los huecos salieron del uso: no había salmón ni pavo en ninguna forma, ni carne picada de pollo,
-- bacon, jamón cocido, kiwi, mango, arándanos, rúcula, boniato, maicena ni bebidas vegetales.
--
-- Cada alta entra con su perfil de caducidad y su ficha de alérgenos. Sin lo segundo, el motor de
-- recomendación es fail-closed: descartaría toda receta que use el ingrediente para cualquier
-- hogar con alergias o dieta declarada.

insert into public.ingredients (name, normalized_name, category)
values
    ('Carne picada de pollo', 'carne picada de pollo', 'Carnes'),
    ('Carne picada mixta', 'carne picada mixta', 'Carnes'),
    ('Contramuslo de pollo', 'contramuslo de pollo', 'Carnes'),
    ('Pechuga de pavo', 'pechuga de pavo', 'Carnes'),
    ('Carne picada de pavo', 'carne picada de pavo', 'Carnes'),
    ('Jamón cocido', 'jamon cocido', 'Carnes'),
    ('Bacon', 'bacon', 'Carnes'),
    ('Chorizo curado', 'chorizo curado', 'Carnes'),
    ('Higadito de pollo', 'higadito de pollo', 'Carnes'),
    ('Salmón', 'salmon', 'Pescados y mariscos'),
    ('Salmón ahumado', 'salmon ahumado', 'Pescados y mariscos'),
    ('Trucha', 'trucha', 'Pescados y mariscos'),
    ('Pez espada', 'pez espada', 'Pescados y mariscos'),
    ('Chipirón', 'chipiron', 'Pescados y mariscos'),
    ('Gulas', 'gulas', 'Pescados y mariscos'),
    ('Langostino cocido', 'langostino cocido', 'Pescados y mariscos'),
    ('Tomate cherry', 'tomate cherry', 'Verduras y hortalizas'),
    ('Rúcula', 'rucula', 'Verduras y hortalizas'),
    ('Canónigos', 'canonigos', 'Verduras y hortalizas'),
    ('Escarola', 'escarola', 'Verduras y hortalizas'),
    ('Endivia', 'endivia', 'Verduras y hortalizas'),
    ('Col lombarda', 'col lombarda', 'Verduras y hortalizas'),
    ('Coles de Bruselas', 'coles de bruselas', 'Verduras y hortalizas'),
    ('Boniato', 'boniato', 'Verduras y hortalizas'),
    ('Pimiento amarillo', 'pimiento amarillo', 'Verduras y hortalizas'),
    ('Seta shiitake', 'seta shiitake', 'Verduras y hortalizas'),
    ('Champiñón portobello', 'champinon portobello', 'Verduras y hortalizas'),
    ('Kiwi', 'kiwi', 'Frutas'),
    ('Mango', 'mango', 'Frutas'),
    ('Arándano', 'arandano', 'Frutas'),
    ('Frambuesa', 'frambuesa', 'Frutas'),
    ('Mora', 'mora', 'Frutas'),
    ('Pomelo', 'pomelo', 'Frutas'),
    ('Dátil', 'datil', 'Frutas'),
    ('Ciruela pasa', 'ciruela pasa', 'Frutas'),
    ('Queso rallado', 'queso rallado', 'Lácteos y huevos'),
    ('Queso feta', 'queso feta', 'Lácteos y huevos'),
    ('Queso mascarpone', 'queso mascarpone', 'Lácteos y huevos'),
    ('Kéfir', 'kefir', 'Lácteos y huevos'),
    ('Leche sin lactosa', 'leche sin lactosa', 'Lácteos y huevos'),
    ('Bebida de avena', 'bebida de avena', 'Lácteos y huevos'),
    ('Bebida de soja', 'bebida de soja', 'Lácteos y huevos'),
    ('Bebida de almendra', 'bebida de almendra', 'Lácteos y huevos'),
    ('Maicena', 'maicena', 'Cereales, pan y pasta'),
    ('Pasta fresca', 'pasta fresca', 'Cereales, pan y pasta'),
    ('Ñoquis', 'noquis', 'Cereales, pan y pasta'),
    ('Pan de pita', 'pan de pita', 'Cereales, pan y pasta'),
    ('Tortilla de trigo', 'tortilla de trigo', 'Cereales, pan y pasta'),
    ('Harina integral', 'harina integral', 'Cereales, pan y pasta'),
    ('Galleta maría', 'galleta maria', 'Cereales, pan y pasta'),
    ('Pepinillo en vinagre', 'pepinillo en vinagre', 'Conservas y otros'),
    ('Alcaparra', 'alcaparra', 'Conservas y otros'),
    ('Maíz dulce en conserva', 'maiz dulce en conserva', 'Conservas y otros'),
    ('Pimiento asado', 'pimiento asado', 'Conservas y otros'),
    ('Alcachofa en conserva', 'alcachofa en conserva', 'Conservas y otros'),
    ('Guisante en conserva', 'guisante en conserva', 'Conservas y otros'),
    ('Aceite de coco', 'aceite de coco', 'Aceites, vinagres y salsas'),
    ('Salsa sriracha', 'salsa sriracha', 'Aceites, vinagres y salsas'),
    ('Salsa teriyaki', 'salsa teriyaki', 'Aceites, vinagres y salsas'),
    ('Salsa césar', 'salsa cesar', 'Aceites, vinagres y salsas'),
    ('Ajo en polvo', 'ajo en polvo', 'Especias y hierbas'),
    ('Jengibre en polvo', 'jengibre en polvo', 'Especias y hierbas'),
    ('Eneldo', 'eneldo', 'Especias y hierbas'),
    ('Salvia', 'salvia', 'Especias y hierbas'),
    ('Estragón', 'estragon', 'Especias y hierbas'),
    ('Cacao en polvo', 'cacao en polvo', 'Condimentos y edulcorantes'),
    ('Azúcar glas', 'azucar glas', 'Condimentos y edulcorantes'),
    ('Sirope de arce', 'sirope de arce', 'Condimentos y edulcorantes')
on conflict (normalized_name) do nothing;

-- Unidad y stock mínimo ya en su forma final: 0022 y 0023 normalizaron las unidades de compra
-- una sola vez y no se reaplican a lo que se dé de alta después.
update public.ingredients i
set default_unit = v.default_unit,
    default_min_stock = v.default_min_stock
from (
  values
    ('carne picada de pollo', 'g', 300),
    ('carne picada mixta', 'g', 300),
    ('contramuslo de pollo', 'ud', 4),
    ('pechuga de pavo', 'g', 300),
    ('carne picada de pavo', 'g', 300),
    ('jamon cocido', 'g', 200),
    ('bacon', 'g', 200),
    ('chorizo curado', 'g', 200),
    ('higadito de pollo', 'g', 250),
    ('salmon', 'g', 250),
    ('salmon ahumado', 'g', 100),
    ('trucha', 'ud', 2),
    ('pez espada', 'g', 300),
    ('chipiron', 'g', 250),
    ('gulas', 'g', 100),
    ('langostino cocido', 'g', 250),
    ('tomate cherry', 'g', 250),
    ('rucula', 'g', 100),
    ('canonigos', 'g', 100),
    ('escarola', 'ud', 1),
    ('endivia', 'ud', 2),
    ('col lombarda', 'ud', 1),
    ('coles de bruselas', 'g', 300),
    ('boniato', 'ud', 2),
    ('pimiento amarillo', 'ud', 2),
    ('seta shiitake', 'g', 150),
    ('champinon portobello', 'g', 200),
    ('kiwi', 'ud', 3),
    ('mango', 'ud', 2),
    ('arandano', 'g', 150),
    ('frambuesa', 'g', 150),
    ('mora', 'g', 150),
    ('pomelo', 'ud', 2),
    ('datil', 'g', 150),
    ('ciruela pasa', 'g', 150),
    ('queso rallado', 'g', 150),
    ('queso feta', 'g', 150),
    ('queso mascarpone', 'g', 150),
    ('kefir', 'ml', 100),
    ('leche sin lactosa', 'l', 0.5),
    ('bebida de avena', 'l', 0.5),
    ('bebida de soja', 'l', 0.5),
    ('bebida de almendra', 'l', 0.5),
    ('maicena', 'g', 250),
    ('pasta fresca', 'g', 250),
    ('noquis', 'g', 500),
    ('pan de pita', 'ud', 4),
    ('tortilla de trigo', 'ud', 6),
    ('harina integral', 'g', 500),
    ('galleta maria', 'paquete', 1),
    ('pepinillo en vinagre', 'bote', 1),
    ('alcaparra', 'bote', 1),
    ('maiz dulce en conserva', 'lata', 1),
    ('pimiento asado', 'bote', 1),
    ('alcachofa en conserva', 'bote', 1),
    ('guisante en conserva', 'bote', 1),
    ('aceite de coco', 'l', 0.5),
    ('salsa sriracha', 'ml', 50),
    ('salsa teriyaki', 'ml', 50),
    ('salsa cesar', 'ml', 50),
    ('ajo en polvo', 'bote', 1),
    ('jengibre en polvo', 'bote', 1),
    ('eneldo', 'bote', 1),
    ('salvia', 'bote', 1),
    ('estragon', 'bote', 1),
    ('cacao en polvo', 'g', 250),
    ('azucar glas', 'g', 250),
    ('sirope de arce', 'ml', 100)
) as v(normalized_name, default_unit, default_min_stock)
where i.normalized_name = v.normalized_name
  and i.default_unit is null;

insert into public.ingredient_expiration_profiles (ingredient_id, profile_id, match_type)
select i.id, m.profile_id, m.match_type
from (
  values
    ('carne picada de pollo', 'meat-poultry-fresh', 'family'),
    ('carne picada mixta', 'meat-sausage-fresh', 'family'),
    ('contramuslo de pollo', 'meat-poultry-fresh', 'direct'),
    ('pechuga de pavo', 'meat-poultry-fresh', 'family'),
    ('carne picada de pavo', 'meat-poultry-fresh', 'family'),
    ('jamon cocido', 'meat-cured-short', 'family'),
    ('bacon', 'meat-bacon', 'direct'),
    ('chorizo curado', 'meat-cured-ham', 'family'),
    ('higadito de pollo', 'meat-offal', 'family'),
    ('salmon', 'fish-fatty', 'direct'),
    ('salmon ahumado', 'fish-desalted', 'fallback'),
    ('trucha', 'fish-fatty', 'direct'),
    ('pez espada', 'fish-lean', 'family'),
    ('chipiron', 'seafood-cephalopod', 'family'),
    ('gulas', 'fish-desalted', 'fallback'),
    ('langostino cocido', 'shellfish-crustacean', 'family'),
    ('tomate cherry', 'vegetable-tomato', 'family'),
    ('rucula', 'vegetable-leafy', 'family'),
    ('canonigos', 'vegetable-leafy', 'family'),
    ('escarola', 'vegetable-lettuce', 'family'),
    ('endivia', 'vegetable-lettuce', 'family'),
    ('col lombarda', 'vegetable-lettuce', 'fallback'),
    ('coles de bruselas', 'vegetable-crucifer', 'family'),
    ('boniato', 'vegetable-potato', 'family'),
    ('pimiento amarillo', 'vegetable-pepper', 'direct'),
    ('seta shiitake', 'vegetable-mushroom', 'family'),
    ('champinon portobello', 'vegetable-mushroom', 'family'),
    ('kiwi', 'fruit-firm', 'family'),
    ('mango', 'fruit-delicate', 'family'),
    ('arandano', 'fruit-berries', 'family'),
    ('frambuesa', 'fruit-berries', 'family'),
    ('mora', 'fruit-berries', 'family'),
    ('pomelo', 'fruit-citrus', 'family'),
    ('datil', 'grain-dry', 'fallback'),
    ('ciruela pasa', 'grain-dry', 'fallback'),
    ('queso rallado', 'cheese-fresh', 'fallback'),
    ('queso feta', 'cheese-fresh', 'family'),
    ('queso mascarpone', 'cheese-cream', 'family'),
    ('kefir', 'dairy-yogurt', 'family'),
    ('leche sin lactosa', 'dairy-milk', 'family'),
    ('bebida de avena', 'dairy-milk', 'fallback'),
    ('bebida de soja', 'dairy-milk', 'fallback'),
    ('bebida de almendra', 'dairy-milk', 'fallback'),
    ('maicena', 'flour-corn', 'family'),
    ('pasta fresca', 'bread-fresh', 'fallback'),
    ('noquis', 'bread-fresh', 'fallback'),
    ('pan de pita', 'bread-packaged', 'family'),
    ('tortilla de trigo', 'bread-packaged', 'family'),
    ('harina integral', 'flour-white', 'family'),
    ('galleta maria', 'bread-dry', 'family'),
    ('pepinillo en vinagre', 'canned-high-acid', 'family'),
    ('alcaparra', 'canned-high-acid', 'family'),
    ('maiz dulce en conserva', 'canned-low-acid', 'family'),
    ('pimiento asado', 'canned-low-acid', 'family'),
    ('alcachofa en conserva', 'canned-low-acid', 'family'),
    ('guisante en conserva', 'canned-low-acid', 'family'),
    ('aceite de coco', 'oil-general', 'family'),
    ('salsa sriracha', 'sauce-shelf', 'family'),
    ('salsa teriyaki', 'sauce-shelf', 'family'),
    ('salsa cesar', 'sauce-refrigerated', 'family'),
    ('ajo en polvo', 'spice-ground', 'family'),
    ('jengibre en polvo', 'spice-ground', 'family'),
    ('eneldo', 'herb-dry', 'family'),
    ('salvia', 'herb-dry', 'family'),
    ('estragon', 'herb-dry', 'family'),
    ('cacao en polvo', 'spice-ground', 'fallback'),
    ('azucar glas', 'sugar-long', 'family'),
    ('sirope de arce', 'honey-long', 'family')
) as m(normalized_name, profile_id, match_type)
join public.ingredients i on i.normalized_name = m.normalized_name
on conflict (ingredient_id) do nothing;

with profile_data (normalized_name, source_ids, source_ref, review_kind, composition_status) as (
  values
    ('carne picada de pollo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: carne picada de pollo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('carne picada mixta', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: carne picada mixta', 'compound_formula_unknown', 'variable_unknown'),
    ('contramuslo de pollo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: contramuslo de pollo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('pechuga de pavo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: pechuga de pavo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('carne picada de pavo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: carne picada de pavo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('jamon cocido', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: jamon cocido', 'compound_formula_unknown', 'variable_unknown'),
    ('bacon', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: bacon', 'compound_formula_unknown', 'variable_unknown'),
    ('chorizo curado', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: chorizo curado', 'compound_formula_unknown', 'variable_unknown'),
    ('higadito de pollo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: higadito de pollo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('salmon', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide']::text[], 'Composición intrínseca revisada desde el nombre catalogado: salmon', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('salmon ahumado', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: salmon ahumado', 'compound_formula_unknown', 'variable_unknown'),
    ('trucha', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide']::text[], 'Composición intrínseca revisada desde el nombre catalogado: trucha', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('pez espada', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide']::text[], 'Composición intrínseca revisada desde el nombre catalogado: pez espada', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('chipiron', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide']::text[], 'Composición intrínseca revisada desde el nombre catalogado: chipiron', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('gulas', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: gulas', 'compound_formula_unknown', 'variable_unknown'),
    ('langostino cocido', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide']::text[], 'Composición intrínseca revisada desde el nombre catalogado: langostino cocido', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('tomate cherry', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: tomate cherry', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('rucula', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: rucula', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('canonigos', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: canonigos', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('escarola', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: escarola', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('endivia', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: endivia', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('col lombarda', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: col lombarda', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('coles de bruselas', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: coles de bruselas', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('boniato', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: boniato', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('pimiento amarillo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: pimiento amarillo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('seta shiitake', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: seta shiitake', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('champinon portobello', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: champinon portobello', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('kiwi', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: kiwi', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('mango', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: mango', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('arandano', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: arandano', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('frambuesa', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: frambuesa', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('mora', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: mora', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('pomelo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: pomelo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('datil', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: datil', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('ciruela pasa', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: ciruela pasa', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('queso rallado', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: queso rallado', 'compound_formula_unknown', 'variable_unknown'),
    ('queso feta', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: queso feta', 'compound_formula_unknown', 'variable_unknown'),
    ('queso mascarpone', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: queso mascarpone', 'compound_formula_unknown', 'variable_unknown'),
    ('kefir', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: kefir', 'compound_formula_unknown', 'variable_unknown'),
    ('leche sin lactosa', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: leche sin lactosa', 'compound_formula_unknown', 'variable_unknown'),
    ('bebida de avena', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: bebida de avena', 'compound_formula_unknown', 'variable_unknown'),
    ('bebida de soja', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: bebida de soja', 'compound_formula_unknown', 'variable_unknown'),
    ('bebida de almendra', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: bebida de almendra', 'compound_formula_unknown', 'variable_unknown'),
    ('maicena', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: maicena', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('pasta fresca', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: pasta fresca', 'compound_formula_unknown', 'variable_unknown'),
    ('noquis', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: noquis', 'compound_formula_unknown', 'variable_unknown'),
    ('pan de pita', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: pan de pita', 'compound_formula_unknown', 'variable_unknown'),
    ('tortilla de trigo', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: tortilla de trigo', 'compound_formula_unknown', 'variable_unknown'),
    ('harina integral', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide']::text[], 'Composición intrínseca revisada desde el nombre catalogado: harina integral', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('galleta maria', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: galleta maria', 'compound_formula_unknown', 'variable_unknown'),
    ('pepinillo en vinagre', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: pepinillo en vinagre', 'compound_formula_unknown', 'variable_unknown'),
    ('alcaparra', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: alcaparra', 'compound_formula_unknown', 'variable_unknown'),
    ('maiz dulce en conserva', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: maiz dulce en conserva', 'compound_formula_unknown', 'variable_unknown'),
    ('pimiento asado', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: pimiento asado', 'compound_formula_unknown', 'variable_unknown'),
    ('alcachofa en conserva', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: alcachofa en conserva', 'compound_formula_unknown', 'variable_unknown'),
    ('guisante en conserva', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: guisante en conserva', 'compound_formula_unknown', 'variable_unknown'),
    ('aceite de coco', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: aceite de coco', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('salsa sriracha', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: salsa sriracha', 'compound_formula_unknown', 'variable_unknown'),
    ('salsa teriyaki', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: salsa teriyaki', 'compound_formula_unknown', 'variable_unknown'),
    ('salsa cesar', array['catalog-name-review', 'eu-1169-annex-ii', 'aesan-allergen-guide', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: salsa cesar', 'compound_formula_unknown', 'variable_unknown'),
    ('ajo en polvo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: ajo en polvo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('jengibre en polvo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: jengibre en polvo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('eneldo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: eneldo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('salvia', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: salvia', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('estragon', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: estragon', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('cacao en polvo', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: cacao en polvo', 'intrinsic_named_ingredient', 'exact_reviewed'),
    ('azucar glas', array['catalog-name-review', 'variable-composition-policy']::text[], 'Nombre genérico sin formulación verificable: azucar glas', 'compound_formula_unknown', 'variable_unknown'),
    ('sirope de arce', array['catalog-name-review']::text[], 'Composición intrínseca revisada desde el nombre catalogado: sirope de arce', 'intrinsic_named_ingredient', 'exact_reviewed')
)
insert into public.ingredient_allergen_profiles (
  ingredient_id, dataset_version, source_ids, source_ref, review_kind, composition_status
)
select i.id, 'ingredient-allergens-es-v1', p.source_ids, p.source_ref, p.review_kind,
       p.composition_status
from profile_data p
join public.ingredients i on i.normalized_name = p.normalized_name
on conflict (ingredient_id) do nothing;

with allergen_data (normalized_name, allergen) as (
  values
    ('carne picada mixta', 'pork'),
    ('jamon cocido', 'pork'),
    ('bacon', 'pork'),
    ('chorizo curado', 'pork'),
    ('salmon', 'fish'),
    ('salmon ahumado', 'fish'),
    ('trucha', 'fish'),
    ('pez espada', 'fish'),
    ('chipiron', 'molluscs'),
    ('gulas', 'fish'),
    ('gulas', 'gluten'),
    ('gulas', 'egg'),
    ('gulas', 'milk'),
    ('gulas', 'soy'),
    ('gulas', 'molluscs'),
    ('langostino cocido', 'crustaceans'),
    ('queso rallado', 'milk'),
    ('queso feta', 'milk'),
    ('queso mascarpone', 'milk'),
    ('kefir', 'milk'),
    ('leche sin lactosa', 'milk'),
    ('bebida de avena', 'gluten'),
    ('bebida de soja', 'soy'),
    ('bebida de almendra', 'nuts'),
    ('pasta fresca', 'gluten'),
    ('pasta fresca', 'egg'),
    ('noquis', 'gluten'),
    ('pan de pita', 'gluten'),
    ('tortilla de trigo', 'gluten'),
    ('harina integral', 'gluten'),
    ('galleta maria', 'gluten'),
    ('galleta maria', 'milk'),
    ('galleta maria', 'soy'),
    ('salsa teriyaki', 'soy'),
    ('salsa teriyaki', 'gluten'),
    ('salsa cesar', 'egg'),
    ('salsa cesar', 'milk'),
    ('salsa cesar', 'fish'),
    ('salsa cesar', 'mustard')
)
insert into public.ingredient_allergen_entries (ingredient_id, allergen)
select i.id, a.allergen
from allergen_data a
join public.ingredients i on i.normalized_name = a.normalized_name
on conflict (ingredient_id, allergen) do nothing;

with diet_data (normalized_name, incompatible_diet) as (
  values
    ('carne picada de pollo', 'vegan'),
    ('carne picada de pollo', 'vegetarian'),
    ('carne picada mixta', 'vegan'),
    ('carne picada mixta', 'vegetarian'),
    ('contramuslo de pollo', 'vegan'),
    ('contramuslo de pollo', 'vegetarian'),
    ('pechuga de pavo', 'vegan'),
    ('pechuga de pavo', 'vegetarian'),
    ('carne picada de pavo', 'vegan'),
    ('carne picada de pavo', 'vegetarian'),
    ('jamon cocido', 'vegan'),
    ('jamon cocido', 'vegetarian'),
    ('bacon', 'vegan'),
    ('bacon', 'vegetarian'),
    ('chorizo curado', 'vegan'),
    ('chorizo curado', 'vegetarian'),
    ('higadito de pollo', 'vegan'),
    ('higadito de pollo', 'vegetarian'),
    ('salmon', 'vegan'),
    ('salmon', 'vegetarian'),
    ('salmon ahumado', 'vegan'),
    ('salmon ahumado', 'vegetarian'),
    ('trucha', 'vegan'),
    ('trucha', 'vegetarian'),
    ('pez espada', 'vegan'),
    ('pez espada', 'vegetarian'),
    ('chipiron', 'vegan'),
    ('chipiron', 'vegetarian'),
    ('gulas', 'vegan'),
    ('gulas', 'vegetarian'),
    ('langostino cocido', 'vegan'),
    ('langostino cocido', 'vegetarian'),
    ('queso rallado', 'vegan'),
    ('queso feta', 'vegan'),
    ('queso mascarpone', 'vegan'),
    ('kefir', 'vegan'),
    ('leche sin lactosa', 'vegan'),
    ('pasta fresca', 'vegan'),
    ('salsa cesar', 'vegan'),
    ('salsa cesar', 'vegetarian')
)
insert into public.ingredient_diet_entries (ingredient_id, incompatible_diet)
select i.id, d.incompatible_diet
from diet_data d
join public.ingredients i on i.normalized_name = d.normalized_name
on conflict (ingredient_id, incompatible_diet) do nothing;
